used_artefacts_all = ['gyro1x_speed_min', 'gyro1x_speed_max', 'gyro1x_speed_avg', 'gyro1x_speed_rms',
                      'gyro1x_speed_crest', 'gyro1x_speed_std', 'gyro1y_speed_min', 'gyro1y_speed_max',
                      'gyro1y_speed_avg', 'gyro1y_speed_rms', 'gyro1y_speed_crest', 'gyro1y_speed_std',
                      'gyro1z_speed_min', 'gyro1z_speed_max', 'gyro1z_speed_avg', 'gyro1z_speed_rms',
                      'gyro1z_speed_crest', 'gyro1z_speed_std', 'gyro1Vec_speed_min', 'gyro1Vec_speed_max',
                      'gyro1Vec_speed_avg', 'gyro1Vec_speed_rms', 'gyro1Vec_speed_crest', 'gyro1Vec_speed_std',
                      'gyro2x_speed_min', 'gyro2x_speed_max', 'gyro2x_speed_avg', 'gyro2x_speed_rms',
                      'gyro2x_speed_crest', 'gyro2x_speed_std', 'gyro2y_speed_min', 'gyro2y_speed_max',
                      'gyro2y_speed_avg', 'gyro2y_speed_rms', 'gyro2y_speed_crest', 'gyro2y_speed_std',
                      'gyro2z_speed_min', 'gyro2z_speed_max', 'gyro2z_speed_avg', 'gyro2z_speed_rms',
                      'gyro2z_speed_crest', 'gyro2z_speed_std', 'gyro2Vec_speed_min', 'gyro2Vec_speed_max',
                      'gyro2Vec_speed_avg', 'gyro2Vec_speed_rms', 'gyro2Vec_speed_crest', 'gyro2Vec_speed_std',
                      'gyro1x_acc_min', 'gyro1x_acc_max', 'gyro1x_acc_avg', 'gyro1x_acc_rms', 'gyro1x_acc_crest',
                      'gyro1x_acc_std', 'gyro1y_acc_min', 'gyro1y_acc_max', 'gyro1y_acc_avg', 'gyro1y_acc_rms',
                      'gyro1y_acc_crest', 'gyro1y_acc_std', 'gyro1z_acc_min', 'gyro1z_acc_max', 'gyro1z_acc_avg',
                      'gyro1z_acc_rms', 'gyro1z_acc_crest', 'gyro1z_acc_std', 'gyro1Vec_acc_min', 'gyro1Vec_acc_max',
                      'gyro1Vec_acc_avg', 'gyro1Vec_acc_rms', 'gyro1Vec_acc_crest', 'gyro1Vec_acc_std',
                      'gyro2x_acc_min', 'gyro2x_acc_max', 'gyro2x_acc_avg', 'gyro2x_acc_rms', 'gyro2x_acc_crest',
                      'gyro2x_acc_std', 'gyro2y_acc_min', 'gyro2y_acc_max', 'gyro2y_acc_avg', 'gyro2y_acc_rms',
                      'gyro2y_acc_crest', 'gyro2y_acc_std', 'gyro2z_acc_min', 'gyro2z_acc_max', 'gyro2z_acc_avg',
                      'gyro2z_acc_rms', 'gyro2z_acc_crest', 'gyro2z_acc_std', 'gyro2Vec_acc_min', 'gyro2Vec_acc_max',
                      'gyro2Vec_acc_avg', 'gyro2Vec_acc_rms', 'gyro2Vec_acc_crest', 'gyro2Vec_acc_std',
                      'gyro1x_angle_min', 'gyro1x_angle_max', 'gyro1x_angle_avg', 'gyro1x_angle_rms',
                      'gyro1x_angle_crest', 'gyro1x_angle_std', 'gyro1y_angle_min', 'gyro1y_angle_max',
                      'gyro1y_angle_avg', 'gyro1y_angle_rms', 'gyro1y_angle_crest', 'gyro1y_angle_std',
                      'gyro1z_angle_min', 'gyro1z_angle_max', 'gyro1z_angle_avg', 'gyro1z_angle_rms',
                      'gyro1z_angle_crest', 'gyro1z_angle_std', 'gyro1Vec_angle_min', 'gyro1Vec_angle_max',
                      'gyro1Vec_angle_avg', 'gyro1Vec_angle_rms', 'gyro1Vec_angle_crest', 'gyro1Vec_angle_std',
                      'gyro2x_angle_min', 'gyro2x_angle_max', 'gyro2x_angle_avg', 'gyro2x_angle_rms',
                      'gyro2x_angle_crest', 'gyro2x_angle_std', 'gyro2y_angle_min', 'gyro2y_angle_max',
                      'gyro2y_angle_avg', 'gyro2y_angle_rms', 'gyro2y_angle_crest', 'gyro2y_angle_std',
                      'gyro2z_angle_min', 'gyro2z_angle_max', 'gyro2z_angle_avg', 'gyro2z_angle_rms',
                      'gyro2z_angle_crest', 'gyro2z_angle_std', 'gyro2Vec_angle_min', 'gyro2Vec_angle_max',
                      'gyro2Vec_angle_avg', 'gyro2Vec_angle_rms', 'gyro2Vec_angle_crest', 'gyro2Vec_angle_std',
                      'gyro1x_power_min', 'gyro1x_power_max', 'gyro1x_power_avg', 'gyro1x_power_rms',
                      'gyro1x_power_crest', 'gyro1x_power_std', 'gyro1y_power_min', 'gyro1y_power_max',
                      'gyro1y_power_avg', 'gyro1y_power_rms', 'gyro1y_power_crest', 'gyro1y_power_std',
                      'gyro1z_power_min', 'gyro1z_power_max', 'gyro1z_power_avg', 'gyro1z_power_rms',
                      'gyro1z_power_crest', 'gyro1z_power_std', 'gyro1Vec_power_min', 'gyro1Vec_power_max',
                      'gyro1Vec_power_avg', 'gyro1Vec_power_rms', 'gyro1Vec_power_crest', 'gyro1Vec_power_std',
                      'gyro2x_power_min', 'gyro2x_power_max', 'gyro2x_power_avg', 'gyro2x_power_rms',
                      'gyro2x_power_crest', 'gyro2x_power_std', 'gyro2y_power_min', 'gyro2y_power_max',
                      'gyro2y_power_avg', 'gyro2y_power_rms', 'gyro2y_power_crest', 'gyro2y_power_std',
                      'gyro2z_power_min', 'gyro2z_power_max', 'gyro2z_power_avg', 'gyro2z_power_rms',
                      'gyro2z_power_crest', 'gyro2z_power_std', 'gyro2Vec_power_min', 'gyro2Vec_power_max',
                      'gyro2Vec_power_avg', 'gyro2Vec_power_rms', 'gyro2Vec_power_crest', 'gyro2Vec_power_std',
                      'gyro2Vec_taps_min', 'gyro2Vec_taps_max', 'gyro2Vec_taps_avg', 'gyro2Vec_taps_rms',
                      'gyro2Vec_taps_crest', 'gyro2Vec_taps_std', 'gyro1x_max_val', 'gyro1x_max_frequency',
                      'gyro1x_delta_frequency', 'gyro1x_median_frequency', 'gyro1x_median_pow',
                      'gyro1x_frequency_ratio', 'gyro1x_median_frequency1', 'gyro1x_median_frequency2',
                      'gyro1x_dc_value', 'gyro1x_frequency_ratio1', 'gyro1y_max_val', 'gyro1y_max_frequency',
                      'gyro1y_delta_frequency', 'gyro1y_median_frequency', 'gyro1y_median_pow',
                      'gyro1y_frequency_ratio', 'gyro1y_median_frequency1', 'gyro1y_median_frequency2',
                      'gyro1y_dc_value', 'gyro1y_frequency_ratio1', 'gyro1z_max_val', 'gyro1z_max_frequency',
                      'gyro1z_delta_frequency', 'gyro1z_median_frequency', 'gyro1z_median_pow',
                      'gyro1z_frequency_ratio', 'gyro1z_median_frequency1', 'gyro1z_median_frequency2',
                      'gyro1z_dc_value', 'gyro1z_frequency_ratio1', 'gyro1Vec_max_val', 'gyro1Vec_max_frequency',
                      'gyro1Vec_delta_frequency', 'gyro1Vec_median_frequency', 'gyro1Vec_median_pow',
                      'gyro1Vec_frequency_ratio', 'gyro1Vec_median_frequency1', 'gyro1Vec_median_frequency2',
                      'gyro1Vec_dc_value', 'gyro1Vec_frequency_ratio1', 'gyro2x_max_val', 'gyro2x_max_frequency',
                      'gyro2x_delta_frequency', 'gyro2x_median_frequency', 'gyro2x_median_pow',
                      'gyro2x_frequency_ratio', 'gyro2x_median_frequency1', 'gyro2x_median_frequency2',
                      'gyro2x_dc_value', 'gyro2x_frequency_ratio1', 'gyro2y_max_val', 'gyro2y_max_frequency',
                      'gyro2y_delta_frequency', 'gyro2y_median_frequency', 'gyro2y_median_pow',
                      'gyro2y_frequency_ratio', 'gyro2y_median_frequency1', 'gyro2y_median_frequency2',
                      'gyro2y_dc_value', 'gyro2y_frequency_ratio1', 'gyro2z_max_val', 'gyro2z_max_frequency',
                      'gyro2z_delta_frequency', 'gyro2z_median_frequency', 'gyro2z_median_pow',
                      'gyro2z_frequency_ratio', 'gyro2z_median_frequency1', 'gyro2z_median_frequency2',
                      'gyro2z_dc_value', 'gyro2z_frequency_ratio1', 'gyro2Vec_max_val', 'gyro2Vec_max_frequency',
                      'gyro2Vec_delta_frequency', 'gyro2Vec_median_frequency', 'gyro2Vec_median_pow',
                      'gyro2Vec_frequency_ratio', 'gyro2Vec_median_frequency1', 'gyro2Vec_median_frequency2',
                      'gyro2Vec_dc_value', 'gyro2Vec_frequency_ratio1', 'gyro1x_max_speed_min', 'gyro1x_max_speed_max',
                      'gyro1x_max_speed_avg', 'gyro1x_max_speed_rms', 'gyro1x_max_speed_crest', 'gyro1x_max_speed_std',
                      'gyro1y_max_speed_min', 'gyro1y_max_speed_max', 'gyro1y_max_speed_avg', 'gyro1y_max_speed_rms',
                      'gyro1y_max_speed_crest', 'gyro1y_max_speed_std', 'gyro1z_max_speed_min', 'gyro1z_max_speed_max',
                      'gyro1z_max_speed_avg', 'gyro1z_max_speed_rms', 'gyro1z_max_speed_crest', 'gyro1z_max_speed_std',
                      'gyro1Vec_max_speed_min', 'gyro1Vec_max_speed_max', 'gyro1Vec_max_speed_avg',
                      'gyro1Vec_max_speed_rms', 'gyro1Vec_max_speed_crest', 'gyro1Vec_max_speed_std',
                      'gyro2x_max_speed_min', 'gyro2x_max_speed_max', 'gyro2x_max_speed_avg', 'gyro2x_max_speed_rms',
                      'gyro2x_max_speed_crest', 'gyro2x_max_speed_std', 'gyro2y_max_speed_min', 'gyro2y_max_speed_max',
                      'gyro2y_max_speed_avg', 'gyro2y_max_speed_rms', 'gyro2y_max_speed_crest', 'gyro2y_max_speed_std',
                      'gyro2z_max_speed_min', 'gyro2z_max_speed_max', 'gyro2z_max_speed_avg', 'gyro2z_max_speed_rms',
                      'gyro2z_max_speed_crest', 'gyro2z_max_speed_std', 'gyro2Vec_max_speed_min',
                      'gyro2Vec_max_speed_max', 'gyro2Vec_max_speed_avg', 'gyro2Vec_max_speed_rms',
                      'gyro2Vec_max_speed_crest', 'gyro2Vec_max_speed_std', 'gyro1x_max_acc_min', 'gyro1x_max_acc_max',
                      'gyro1x_max_acc_avg', 'gyro1x_max_acc_rms', 'gyro1x_max_acc_crest', 'gyro1x_max_acc_std',
                      'gyro1y_max_acc_min', 'gyro1y_max_acc_max', 'gyro1y_max_acc_avg', 'gyro1y_max_acc_rms',
                      'gyro1y_max_acc_crest', 'gyro1y_max_acc_std', 'gyro1z_max_acc_min', 'gyro1z_max_acc_max',
                      'gyro1z_max_acc_avg', 'gyro1z_max_acc_rms', 'gyro1z_max_acc_crest', 'gyro1z_max_acc_std',
                      'gyro1Vec_max_acc_min', 'gyro1Vec_max_acc_max', 'gyro1Vec_max_acc_avg', 'gyro1Vec_max_acc_rms',
                      'gyro1Vec_max_acc_crest', 'gyro1Vec_max_acc_std', 'gyro2x_max_acc_min', 'gyro2x_max_acc_max',
                      'gyro2x_max_acc_avg', 'gyro2x_max_acc_rms', 'gyro2x_max_acc_crest', 'gyro2x_max_acc_std',
                      'gyro2y_max_acc_min', 'gyro2y_max_acc_max', 'gyro2y_max_acc_avg', 'gyro2y_max_acc_rms',
                      'gyro2y_max_acc_crest', 'gyro2y_max_acc_std', 'gyro2z_max_acc_min', 'gyro2z_max_acc_max',
                      'gyro2z_max_acc_avg', 'gyro2z_max_acc_rms', 'gyro2z_max_acc_crest', 'gyro2z_max_acc_std',
                      'gyro2Vec_max_acc_min', 'gyro2Vec_max_acc_max', 'gyro2Vec_max_acc_avg', 'gyro2Vec_max_acc_rms',
                      'gyro2Vec_max_acc_crest', 'gyro2Vec_max_acc_std', 'gyro1x_max_angle_min', 'gyro1x_max_angle_max',
                      'gyro1x_max_angle_avg', 'gyro1x_max_angle_rms', 'gyro1x_max_angle_crest', 'gyro1x_max_angle_std',
                      'gyro1y_max_angle_min', 'gyro1y_max_angle_max', 'gyro1y_max_angle_avg', 'gyro1y_max_angle_rms',
                      'gyro1y_max_angle_crest', 'gyro1y_max_angle_std', 'gyro1z_max_angle_min', 'gyro1z_max_angle_max',
                      'gyro1z_max_angle_avg', 'gyro1z_max_angle_rms', 'gyro1z_max_angle_crest', 'gyro1z_max_angle_std',
                      'gyro1Vec_max_angle_min', 'gyro1Vec_max_angle_max', 'gyro1Vec_max_angle_avg',
                      'gyro1Vec_max_angle_rms', 'gyro1Vec_max_angle_crest', 'gyro1Vec_max_angle_std',
                      'gyro2x_max_angle_min', 'gyro2x_max_angle_max', 'gyro2x_max_angle_avg', 'gyro2x_max_angle_rms',
                      'gyro2x_max_angle_crest', 'gyro2x_max_angle_std', 'gyro2y_max_angle_min', 'gyro2y_max_angle_max',
                      'gyro2y_max_angle_avg', 'gyro2y_max_angle_rms', 'gyro2y_max_angle_crest', 'gyro2y_max_angle_std',
                      'gyro2z_max_angle_min', 'gyro2z_max_angle_max', 'gyro2z_max_angle_avg', 'gyro2z_max_angle_rms',
                      'gyro2z_max_angle_crest', 'gyro2z_max_angle_std', 'gyro2Vec_max_angle_min',
                      'gyro2Vec_max_angle_max', 'gyro2Vec_max_angle_avg', 'gyro2Vec_max_angle_rms',
                      'gyro2Vec_max_angle_crest', 'gyro2Vec_max_angle_std', 'gyro1x_max_power_min',
                      'gyro1x_max_power_max', 'gyro1x_max_power_avg', 'gyro1x_max_power_rms', 'gyro1x_max_power_crest',
                      'gyro1x_max_power_std', 'gyro1y_max_power_min', 'gyro1y_max_power_max', 'gyro1y_max_power_avg',
                      'gyro1y_max_power_rms', 'gyro1y_max_power_crest', 'gyro1y_max_power_std', 'gyro1z_max_power_min',
                      'gyro1z_max_power_max', 'gyro1z_max_power_avg', 'gyro1z_max_power_rms', 'gyro1z_max_power_crest',
                      'gyro1z_max_power_std', 'gyro1Vec_max_power_min', 'gyro1Vec_max_power_max',
                      'gyro1Vec_max_power_avg', 'gyro1Vec_max_power_rms', 'gyro1Vec_max_power_crest',
                      'gyro1Vec_max_power_std', 'gyro2x_max_power_min', 'gyro2x_max_power_max', 'gyro2x_max_power_avg',
                      'gyro2x_max_power_rms', 'gyro2x_max_power_crest', 'gyro2x_max_power_std', 'gyro2y_max_power_min',
                      'gyro2y_max_power_max', 'gyro2y_max_power_avg', 'gyro2y_max_power_rms', 'gyro2y_max_power_crest',
                      'gyro2y_max_power_std', 'gyro2z_max_power_min', 'gyro2z_max_power_max', 'gyro2z_max_power_avg',
                      'gyro2z_max_power_rms', 'gyro2z_max_power_crest', 'gyro2z_max_power_std',
                      'gyro2Vec_max_power_min', 'gyro2Vec_max_power_max', 'gyro2Vec_max_power_avg',
                      'gyro2Vec_max_power_rms', 'gyro2Vec_max_power_crest', 'gyro2Vec_max_power_std',

                      ]

used_artefacts_gyro1Vec = ['gyro1Vec_speed_min', 'gyro1Vec_speed_max', 'gyro1Vec_speed_avg', 'gyro1Vec_speed_rms',
                           'gyro1Vec_speed_crest', 'gyro1Vec_speed_std', 'gyro1Vec_acc_min', 'gyro1Vec_acc_max',
                           'gyro1Vec_acc_avg', 'gyro1Vec_acc_rms', 'gyro1Vec_acc_crest', 'gyro1Vec_acc_std',
                           'gyro1Vec_angle_min', 'gyro1Vec_angle_max', 'gyro1Vec_angle_avg', 'gyro1Vec_angle_rms',
                           'gyro1Vec_angle_crest', 'gyro1Vec_angle_std', 'gyro1Vec_power_min', 'gyro1Vec_power_max',
                           'gyro1Vec_power_avg', 'gyro1Vec_power_rms', 'gyro1Vec_power_crest', 'gyro1Vec_power_std',
                           'gyro1Vec_taps_min', 'gyro1Vec_taps_max', 'gyro1Vec_taps_avg', 'gyro1Vec_taps_rms',
                           'gyro1Vec_taps_crest', 'gyro1Vec_taps_std', 'gyro1Vec_max_val', 'gyro1Vec_max_frequency',
                           'gyro1Vec_delta_frequency', 'gyro1Vec_median_frequency', 'gyro1Vec_median_pow',
                           'gyro1Vec_frequency_ratio', 'gyro1Vec_median_frequency1', 'gyro1Vec_median_frequency2',
                           'gyro1Vec_dc_value', 'gyro1Vec_frequency_ratio1', 'gyro1Vec_max_speed_min',
                           'gyro1Vec_max_speed_max', 'gyro1Vec_max_speed_avg', 'gyro1Vec_max_speed_rms',
                           'gyro1Vec_max_speed_crest', 'gyro1Vec_max_speed_std', 'gyro1Vec_max_acc_min',
                           'gyro1Vec_max_acc_max', 'gyro1Vec_max_acc_avg', 'gyro1Vec_max_acc_rms',
                           'gyro1Vec_max_acc_crest', 'gyro1Vec_max_acc_std', 'gyro1Vec_max_angle_min',
                           'gyro1Vec_max_angle_max', 'gyro1Vec_max_angle_avg', 'gyro1Vec_max_angle_rms',
                           'gyro1Vec_max_angle_crest', 'gyro1Vec_max_angle_std', 'gyro1Vec_max_power_min',
                           'gyro1Vec_max_power_max', 'gyro1Vec_max_power_avg', 'gyro1Vec_max_power_rms',
                           'gyro1Vec_max_power_crest', 'gyro1Vec_max_power_std']

used_artefacts_gyro1x = ['gyro1x_speed_min', 'gyro1x_speed_max', 'gyro1x_speed_avg', 'gyro1x_speed_rms',
                         'gyro1x_speed_crest', 'gyro1x_speed_std', 'gyro1x_acc_min', 'gyro1x_acc_max',
                         'gyro1x_acc_avg', 'gyro1x_acc_rms', 'gyro1x_acc_crest', 'gyro1x_acc_std',
                         'gyro1x_angle_min', 'gyro1x_angle_max', 'gyro1x_angle_avg', 'gyro1x_angle_rms',
                         'gyro1x_angle_crest', 'gyro1x_angle_std', 'gyro1x_power_min', 'gyro1x_power_max',
                         'gyro1x_power_avg', 'gyro1x_power_rms', 'gyro1x_power_crest', 'gyro1x_power_std',
                         'gyro1x_taps_min', 'gyro1x_taps_max', 'gyro1x_taps_avg', 'gyro1x_taps_rms',
                         'gyro1x_taps_crest', 'gyro1x_taps_std', 'gyro1x_max_val', 'gyro1x_max_frequency',
                         'gyro1x_delta_frequency', 'gyro1x_median_frequency', 'gyro1x_median_pow',
                         'gyro1x_frequency_ratio', 'gyro1x_median_frequency1', 'gyro1x_median_frequency2',
                         'gyro1x_dc_value', 'gyro1x_frequency_ratio1', 'gyro1x_max_speed_min',
                         'gyro1x_max_speed_max', 'gyro1x_max_speed_avg', 'gyro1x_max_speed_rms',
                         'gyro1x_max_speed_crest', 'gyro1x_max_speed_std', 'gyro1x_max_acc_min',
                         'gyro1x_max_acc_max', 'gyro1x_max_acc_avg', 'gyro1x_max_acc_rms',
                         'gyro1x_max_acc_crest', 'gyro1x_max_acc_std', 'gyro1x_max_angle_min',
                         'gyro1x_max_angle_max', 'gyro1x_max_angle_avg', 'gyro1x_max_angle_rms',
                         'gyro1x_max_angle_crest', 'gyro1x_max_angle_std', 'gyro1x_max_power_min',
                         'gyro1x_max_power_max', 'gyro1x_max_power_avg', 'gyro1x_max_power_rms',
                         'gyro1x_max_power_crest', 'gyro1x_max_power_std']

used_artefacts_gyro1y = ['gyro1y_speed_min', 'gyro1y_speed_max', 'gyro1y_speed_avg', 'gyro1y_speed_rms',
                         'gyro1y_speed_crest', 'gyro1y_speed_std', 'gyro1y_acc_min', 'gyro1y_acc_max',
                         'gyro1y_acc_avg', 'gyro1y_acc_rms', 'gyro1y_acc_crest', 'gyro1y_acc_std',
                         'gyro1y_angle_min', 'gyro1y_angle_max', 'gyro1y_angle_avg', 'gyro1y_angle_rms',
                         'gyro1y_angle_crest', 'gyro1y_angle_std', 'gyro1y_power_min', 'gyro1y_power_max',
                         'gyro1y_power_avg', 'gyro1y_power_rms', 'gyro1y_power_crest', 'gyro1y_power_std',
                         'gyro1y_taps_min', 'gyro1y_taps_max', 'gyro1y_taps_avg', 'gyro1y_taps_rms',
                         'gyro1y_taps_crest', 'gyro1y_taps_std', 'gyro1y_max_val', 'gyro1y_max_frequency',
                         'gyro1y_delta_frequency', 'gyro1y_median_frequency', 'gyro1y_median_pow',
                         'gyro1y_frequency_ratio', 'gyro1y_median_frequency1', 'gyro1y_median_frequency2',
                         'gyro1y_dc_value', 'gyro1y_frequency_ratio1', 'gyro1y_max_speed_min',
                         'gyro1y_max_speed_max', 'gyro1y_max_speed_avg', 'gyro1y_max_speed_rms',
                         'gyro1y_max_speed_crest', 'gyro1y_max_speed_std', 'gyro1y_max_acc_min',
                         'gyro1y_max_acc_max', 'gyro1y_max_acc_avg', 'gyro1y_max_acc_rms',
                         'gyro1y_max_acc_crest', 'gyro1y_max_acc_std', 'gyro1y_max_angle_min',
                         'gyro1y_max_angle_max', 'gyro1y_max_angle_avg', 'gyro1y_max_angle_rms',
                         'gyro1y_max_angle_crest', 'gyro1y_max_angle_std', 'gyro1y_max_power_min',
                         'gyro1y_max_power_max', 'gyro1y_max_power_avg', 'gyro1y_max_power_rms',
                         'gyro1y_max_power_crest', 'gyro1y_max_power_std']

used_artefacts_gyro1z = ['gyro1z_speed_min', 'gyro1z_speed_max', 'gyro1z_speed_avg', 'gyro1z_speed_rms',
                         'gyro1z_speed_crest', 'gyro1z_speed_std', 'gyro1z_acc_min', 'gyro1z_acc_max',
                         'gyro1z_acc_avg', 'gyro1z_acc_rms', 'gyro1z_acc_crest', 'gyro1z_acc_std',
                         'gyro1z_angle_min', 'gyro1z_angle_max', 'gyro1z_angle_avg', 'gyro1z_angle_rms',
                         'gyro1z_angle_crest', 'gyro1z_angle_std', 'gyro1z_power_min', 'gyro1z_power_max',
                         'gyro1z_power_avg', 'gyro1z_power_rms', 'gyro1z_power_crest', 'gyro1z_power_std',
                         'gyro1z_taps_min', 'gyro1z_taps_max', 'gyro1z_taps_avg', 'gyro1z_taps_rms',
                         'gyro1z_taps_crest', 'gyro1z_taps_std', 'gyro1z_max_val', 'gyro1z_max_frequency',
                         'gyro1z_delta_frequency', 'gyro1z_median_frequency', 'gyro1z_median_pow',
                         'gyro1z_frequency_ratio', 'gyro1z_median_frequency1', 'gyro1z_median_frequency2',
                         'gyro1z_dc_value', 'gyro1z_frequency_ratio1', 'gyro1z_max_speed_min',
                         'gyro1z_max_speed_max', 'gyro1z_max_speed_avg', 'gyro1z_max_speed_rms',
                         'gyro1z_max_speed_crest', 'gyro1z_max_speed_std', 'gyro1z_max_acc_min',
                         'gyro1z_max_acc_max', 'gyro1z_max_acc_avg', 'gyro1z_max_acc_rms',
                         'gyro1z_max_acc_crest', 'gyro1z_max_acc_std', 'gyro1z_max_angle_min',
                         'gyro1z_max_angle_max', 'gyro1z_max_angle_avg', 'gyro1z_max_angle_rms',
                         'gyro1z_max_angle_crest', 'gyro1z_max_angle_std', 'gyro1z_max_power_min',
                         'gyro1z_max_power_max', 'gyro1z_max_power_avg', 'gyro1z_max_power_rms',
                         'gyro1z_max_power_crest', 'gyro1z_max_power_std']

used_artefacts_gyro2Vec = ['gyro2Vec_speed_min', 'gyro2Vec_speed_max', 'gyro2Vec_speed_avg', 'gyro2Vec_speed_rms',
                           'gyro2Vec_speed_crest', 'gyro2Vec_speed_std', 'gyro2Vec_acc_min', 'gyro2Vec_acc_max',
                           'gyro2Vec_acc_avg', 'gyro2Vec_acc_rms', 'gyro2Vec_acc_crest', 'gyro2Vec_acc_std',
                           'gyro2Vec_angle_min', 'gyro2Vec_angle_max', 'gyro2Vec_angle_avg', 'gyro2Vec_angle_rms',
                           'gyro2Vec_angle_crest', 'gyro2Vec_angle_std', 'gyro2Vec_power_min', 'gyro2Vec_power_max',
                           'gyro2Vec_power_avg', 'gyro2Vec_power_rms', 'gyro2Vec_power_crest', 'gyro2Vec_power_std',
                           'gyro2Vec_taps_min', 'gyro2Vec_taps_max', 'gyro2Vec_taps_avg', 'gyro2Vec_taps_rms',
                           'gyro2Vec_taps_crest', 'gyro2Vec_taps_std', 'gyro2Vec_max_val', 'gyro2Vec_max_frequency',
                           'gyro2Vec_delta_frequency', 'gyro2Vec_median_frequency', 'gyro2Vec_median_pow',
                           'gyro2Vec_frequency_ratio', 'gyro2Vec_median_frequency1', 'gyro2Vec_median_frequency2',
                           'gyro2Vec_dc_value', 'gyro2Vec_frequency_ratio1', 'gyro2Vec_max_speed_min',
                           'gyro2Vec_max_speed_max', 'gyro2Vec_max_speed_avg', 'gyro2Vec_max_speed_rms',
                           'gyro2Vec_max_speed_crest', 'gyro2Vec_max_speed_std', 'gyro2Vec_max_acc_min',
                           'gyro2Vec_max_acc_max', 'gyro2Vec_max_acc_avg', 'gyro2Vec_max_acc_rms',
                           'gyro2Vec_max_acc_crest', 'gyro2Vec_max_acc_std', 'gyro2Vec_max_angle_min',
                           'gyro2Vec_max_angle_max', 'gyro2Vec_max_angle_avg', 'gyro2Vec_max_angle_rms',
                           'gyro2Vec_max_angle_crest', 'gyro2Vec_max_angle_std', 'gyro2Vec_max_power_min',
                           'gyro2Vec_max_power_max', 'gyro2Vec_max_power_avg', 'gyro2Vec_max_power_rms',
                           'gyro2Vec_max_power_crest', 'gyro2Vec_max_power_std']

used_artefacts_gyro2x = ['gyro2x_speed_min', 'gyro2x_speed_max', 'gyro2x_speed_avg', 'gyro2x_speed_rms',
                         'gyro2x_speed_crest', 'gyro2x_speed_std', 'gyro2x_acc_min', 'gyro2x_acc_max',
                         'gyro2x_acc_avg', 'gyro2x_acc_rms', 'gyro2x_acc_crest', 'gyro2x_acc_std',
                         'gyro2x_angle_min', 'gyro2x_angle_max', 'gyro2x_angle_avg', 'gyro2x_angle_rms',
                         'gyro2x_angle_crest', 'gyro2x_angle_std', 'gyro2x_power_min', 'gyro2x_power_max',
                         'gyro2x_power_avg', 'gyro2x_power_rms', 'gyro2x_power_crest', 'gyro2x_power_std',
                         'gyro2x_taps_min', 'gyro2x_taps_max', 'gyro2x_taps_avg', 'gyro2x_taps_rms',
                         'gyro2x_taps_crest', 'gyro2x_taps_std', 'gyro2x_max_val', 'gyro2x_max_frequency',
                         'gyro2x_delta_frequency', 'gyro2x_median_frequency', 'gyro2x_median_pow',
                         'gyro2x_frequency_ratio', 'gyro2x_median_frequency1', 'gyro2x_median_frequency2',
                         'gyro2x_dc_value', 'gyro2x_frequency_ratio1', 'gyro2x_max_speed_min',
                         'gyro2x_max_speed_max', 'gyro2x_max_speed_avg', 'gyro2x_max_speed_rms',
                         'gyro2x_max_speed_crest', 'gyro2x_max_speed_std', 'gyro2x_max_acc_min',
                         'gyro2x_max_acc_max', 'gyro2x_max_acc_avg', 'gyro2x_max_acc_rms',
                         'gyro2x_max_acc_crest', 'gyro2x_max_acc_std', 'gyro2x_max_angle_min',
                         'gyro2x_max_angle_max', 'gyro2x_max_angle_avg', 'gyro2x_max_angle_rms',
                         'gyro2x_max_angle_crest', 'gyro2x_max_angle_std', 'gyro2x_max_power_min',
                         'gyro2x_max_power_max', 'gyro2x_max_power_avg', 'gyro2x_max_power_rms',
                         'gyro2x_max_power_crest', 'gyro2x_max_power_std']

used_artefacts_gyro2y = ['gyro2y_speed_min', 'gyro2y_speed_max', 'gyro2y_speed_avg', 'gyro2y_speed_rms',
                         'gyro2y_speed_crest', 'gyro2y_speed_std', 'gyro2y_acc_min', 'gyro2y_acc_max',
                         'gyro2y_acc_avg', 'gyro2y_acc_rms', 'gyro2y_acc_crest', 'gyro2y_acc_std',
                         'gyro2y_angle_min', 'gyro2y_angle_max', 'gyro2y_angle_avg', 'gyro2y_angle_rms',
                         'gyro2y_angle_crest', 'gyro2y_angle_std', 'gyro2y_power_min', 'gyro2y_power_max',
                         'gyro2y_power_avg', 'gyro2y_power_rms', 'gyro2y_power_crest', 'gyro2y_power_std',
                         'gyro2y_taps_min', 'gyro2y_taps_max', 'gyro2y_taps_avg', 'gyro2y_taps_rms',
                         'gyro2y_taps_crest', 'gyro2y_taps_std', 'gyro2y_max_val', 'gyro2y_max_frequency',
                         'gyro2y_delta_frequency', 'gyro2y_median_frequency', 'gyro2y_median_pow',
                         'gyro2y_frequency_ratio', 'gyro2y_median_frequency1', 'gyro2y_median_frequency2',
                         'gyro2y_dc_value', 'gyro2y_frequency_ratio1', 'gyro2y_max_speed_min',
                         'gyro2y_max_speed_max', 'gyro2y_max_speed_avg', 'gyro2y_max_speed_rms',
                         'gyro2y_max_speed_crest', 'gyro2y_max_speed_std', 'gyro2y_max_acc_min',
                         'gyro2y_max_acc_max', 'gyro2y_max_acc_avg', 'gyro2y_max_acc_rms',
                         'gyro2y_max_acc_crest', 'gyro2y_max_acc_std', 'gyro2y_max_angle_min',
                         'gyro2y_max_angle_max', 'gyro2y_max_angle_avg', 'gyro2y_max_angle_rms',
                         'gyro2y_max_angle_crest', 'gyro2y_max_angle_std', 'gyro2y_max_power_min',
                         'gyro2y_max_power_max', 'gyro2y_max_power_avg', 'gyro2y_max_power_rms',
                         'gyro2y_max_power_crest', 'gyro2y_max_power_std']

used_artefacts_gyro2z = ['gyro2z_speed_min', 'gyro2z_speed_max', 'gyro2z_speed_avg', 'gyro2z_speed_rms',
                         'gyro2z_speed_crest', 'gyro2z_speed_std', 'gyro2z_acc_min', 'gyro2z_acc_max',
                         'gyro2z_acc_avg', 'gyro2z_acc_rms', 'gyro2z_acc_crest', 'gyro2z_acc_std',
                         'gyro2z_angle_min', 'gyro2z_angle_max', 'gyro2z_angle_avg', 'gyro2z_angle_rms',
                         'gyro2z_angle_crest', 'gyro2z_angle_std', 'gyro2z_power_min', 'gyro2z_power_max',
                         'gyro2z_power_avg', 'gyro2z_power_rms', 'gyro2z_power_crest', 'gyro2z_power_std',
                         'gyro2z_taps_min', 'gyro2z_taps_max', 'gyro2z_taps_avg', 'gyro2z_taps_rms',
                         'gyro2z_taps_crest', 'gyro2z_taps_std', 'gyro2z_max_val', 'gyro2z_max_frequency',
                         'gyro2z_delta_frequency', 'gyro2z_median_frequency', 'gyro2z_median_pow',
                         'gyro2z_frequency_ratio', 'gyro2z_median_frequency1', 'gyro2z_median_frequency2',
                         'gyro2z_dc_value', 'gyro2z_frequency_ratio1', 'gyro2z_max_speed_min',
                         'gyro2z_max_speed_max', 'gyro2z_max_speed_avg', 'gyro2z_max_speed_rms',
                         'gyro2z_max_speed_crest', 'gyro2z_max_speed_std', 'gyro2z_max_acc_min',
                         'gyro2z_max_acc_max', 'gyro2z_max_acc_avg', 'gyro2z_max_acc_rms',
                         'gyro2z_max_acc_crest', 'gyro2z_max_acc_std', 'gyro2z_max_angle_min',
                         'gyro2z_max_angle_max', 'gyro2z_max_angle_avg', 'gyro2z_max_angle_rms',
                         'gyro2z_max_angle_crest', 'gyro2z_max_angle_std', 'gyro2z_max_power_min',
                         'gyro2z_max_power_max', 'gyro2z_max_power_avg', 'gyro2z_max_power_rms',
                         'gyro2z_max_power_crest', 'gyro2z_max_power_std']

used_artefacts_mix1 = ['gyro2y_speed_max', 'gyro2y_speed_avg', 'gyro2y_speed_rms', 'gyro2y_speed_crest',

                       'gyro2y_acc_max', 'gyro2y_acc_rms', 'gyro2y_acc_crest',

                       'gyro2y_max_angle_max', 'gyro2y_max_angle_rms', 'gyro2y_max_angle_crest',

                       'gyro2y_power_max', 'gyro2y_power_avg', 'gyro2y_power_rms', 'gyro2y_power_crest',

                       'gyro2y_taps_min', 'gyro2y_taps_max', 'gyro2y_taps_avg',

                       'gyro2y_max_val', 'gyro2y_delta_frequency', 'gyro2y_median_frequency', 'gyro2y_median_pow',
                       'gyro2y_frequency_ratio', 'gyro2y_median_frequency1', 'gyro2y_median_frequency2']

used_artefacts_mix2 = ['gyro1Vec_frequency_ratio', 'gyro2Vec_frequency_ratio', 'gyro1y_frequency_ratio',
                       'gyro1z_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro1x_speed_max',
                       'gyro2y_speed_crest', 'gyro2Vec_max_angle_crest', 'gyro2Vec_max_angle_max', 'gyro1y_taps_max',
                       'gyro2Vec_taps_min', 'gyro2Vec_median_frequency', 'gyro2y_median_frequency2']

used_artefacts_mix3 = ['gyro2Vec_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro2y_frequency_ratio',
                       'gyro2z_frequency_ratio', 'gyro2Vec_speed_crest', 'gyro2Vec_acc_crest',
                       'gyro2Vec_max_angle_crest', 'gyro2Vec_power_crest', 'gyro2Vec_delta_frequency',
                       'gyro2Vec_median_frequency', 'gyro2Vec_median_pow']

used_artefacts_mix4 = ['gyro2x_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro2z_frequency_ratio',
                       'gyro2z_frequency_ratio', 'gyro2Vec_speed_crest', 'gyro2Vec_acc_crest',
                       'gyro2Vec_max_angle_crest', 'gyro2Vec_power_crest', 'gyro2Vec_delta_frequency',
                       'gyro2Vec_median_frequency', 'gyro2Vec_median_pow']

used_artefacts_mix5 = ['gyro1x_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro1z_frequency_ratio',
                       'gyro2z_frequency_ratio', 'gyro2Vec_speed_crest', 'gyro2Vec_acc_crest',
                       'gyro2Vec_max_angle_crest', 'gyro2Vec_power_crest', 'gyro2Vec_delta_frequency',
                       'gyro2Vec_median_frequency', 'gyro2Vec_median_pow']

used_artefacts_min4 = ['gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2Vec_max_angle_crest',
                       'gyro2Vec_median_frequency']

used_artefacts_mix6 = ['gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2Vec_max_angle_crest',
                       'gyro2Vec_median_frequency', 'gyro1x_speed_min', 'gyro1x_speed_max', 'gyro1x_speed_avg',
                       'gyro1x_speed_rms', 'gyro1x_speed_crest', 'gyro1y_speed_min', 'gyro1y_speed_max',
                       'gyro1y_speed_avg', 'gyro1y_speed_rms', 'gyro1y_speed_crest', 'gyro1z_speed_min',
                       'gyro1z_speed_max', 'gyro1z_speed_avg', 'gyro1z_speed_rms', 'gyro1z_speed_crest',
                       'gyro1Vec_speed_min', 'gyro1Vec_speed_max', 'gyro1Vec_speed_avg', 'gyro1Vec_speed_rms',
                       'gyro1Vec_speed_crest', 'gyro2x_speed_min', 'gyro2x_speed_max', 'gyro2x_speed_avg',
                       'gyro2x_speed_rms', 'gyro2x_speed_crest', 'gyro2y_speed_min', 'gyro2y_speed_max',
                       'gyro2y_speed_avg', 'gyro2y_speed_rms', 'gyro2y_speed_crest', 'gyro2z_speed_min',
                       'gyro2z_speed_max', 'gyro2z_speed_avg', 'gyro2z_speed_rms', 'gyro2z_speed_crest',
                       'gyro2Vec_speed_min', 'gyro2Vec_speed_max', 'gyro2Vec_speed_avg', 'gyro2Vec_speed_rms',
                       'gyro2Vec_speed_crest', 'gyro1x_acc_min', 'gyro1x_acc_max', 'gyro1x_acc_avg', 'gyro1x_acc_rms',
                       'gyro1x_acc_crest', 'gyro1y_acc_min', 'gyro1y_acc_max', 'gyro1y_acc_avg', 'gyro1y_acc_rms',
                       'gyro1y_acc_crest', 'gyro1z_acc_min', 'gyro1z_acc_max', 'gyro1z_acc_avg', 'gyro1z_acc_rms',
                       'gyro1z_acc_crest', 'gyro1Vec_acc_min', 'gyro1Vec_acc_max', 'gyro1Vec_acc_avg',
                       'gyro1Vec_acc_rms', 'gyro1Vec_acc_crest', 'gyro2x_acc_min', 'gyro2x_acc_max', 'gyro2x_acc_avg',
                       'gyro2x_acc_rms', 'gyro2x_acc_crest', 'gyro2y_acc_min', 'gyro2y_acc_max', 'gyro2y_acc_avg',
                       'gyro2y_acc_rms', 'gyro2y_acc_crest', 'gyro2z_acc_min', 'gyro2z_acc_max', 'gyro2z_acc_avg',
                       'gyro2z_acc_rms', 'gyro2z_acc_crest', 'gyro2Vec_acc_min', 'gyro2Vec_acc_max', 'gyro2Vec_acc_avg',
                       'gyro2Vec_acc_rms', 'gyro2Vec_acc_crest', 'gyro1x_max_angle_min', 'gyro1x_max_angle_max',
                       'gyro1x_max_angle_avg', 'gyro1x_max_angle_rms', 'gyro1x_max_angle_crest', 'gyro1y_max_angle_min',
                       'gyro1y_max_angle_max', 'gyro1y_max_angle_avg', 'gyro1y_max_angle_rms', 'gyro1y_max_angle_crest',
                       'gyro1z_max_angle_min', 'gyro1z_max_angle_max', 'gyro1z_max_angle_avg', 'gyro1z_max_angle_rms',
                       'gyro1z_max_angle_crest', 'gyro1Vec_max_angle_min', 'gyro1Vec_max_angle_max',
                       'gyro1Vec_max_angle_avg', 'gyro1Vec_max_angle_rms', 'gyro1Vec_max_angle_crest',
                       'gyro2x_max_angle_min', 'gyro2x_max_angle_max', 'gyro2x_max_angle_avg', 'gyro2x_max_angle_rms',
                       'gyro2x_max_angle_crest', 'gyro2y_max_angle_min', 'gyro2y_max_angle_max', 'gyro2y_max_angle_avg',
                       'gyro2y_max_angle_rms', 'gyro2y_max_angle_crest', 'gyro2z_max_angle_min', 'gyro2z_max_angle_max',
                       'gyro2z_max_angle_avg', 'gyro2z_max_angle_rms', 'gyro2z_max_angle_crest',
                       'gyro2Vec_max_angle_min', 'gyro2Vec_max_angle_max', 'gyro2Vec_max_angle_avg',
                       'gyro2Vec_max_angle_rms', 'gyro1x_power_min', 'gyro1x_power_max', 'gyro1x_power_avg',
                       'gyro1x_power_rms', 'gyro1x_power_crest', 'gyro1y_power_min', 'gyro1y_power_max',
                       'gyro1y_power_avg', 'gyro1y_power_rms', 'gyro1y_power_crest', 'gyro1z_power_min',
                       'gyro1z_power_max', 'gyro1z_power_avg', 'gyro1z_power_rms', 'gyro1z_power_crest',
                       'gyro1Vec_power_min', 'gyro1Vec_power_max', 'gyro1Vec_power_avg', 'gyro1Vec_power_rms',
                       'gyro1Vec_power_crest', 'gyro2x_power_min', 'gyro2x_power_max', 'gyro2x_power_avg',
                       'gyro2x_power_rms', 'gyro2x_power_crest', 'gyro2y_power_min', 'gyro2y_power_max',
                       'gyro2y_power_avg', 'gyro2y_power_rms', 'gyro2y_power_crest', 'gyro2z_power_min',
                       'gyro2z_power_max', 'gyro2z_power_avg', 'gyro2z_power_rms', 'gyro2z_power_crest',
                       'gyro2Vec_power_min', 'gyro2Vec_power_max', 'gyro2Vec_power_avg', 'gyro2Vec_power_rms',
                       'gyro2Vec_power_crest', 'gyro1x_taps_min', 'gyro1x_taps_max', 'gyro1x_taps_avg',
                       'gyro1x_taps_rms', 'gyro1x_taps_crest', 'gyro1y_taps_min', 'gyro1y_taps_max', 'gyro1y_taps_avg',
                       'gyro1y_taps_rms', 'gyro1y_taps_crest', 'gyro1z_taps_min', 'gyro1z_taps_max', 'gyro1z_taps_avg',
                       'gyro1z_taps_rms', 'gyro1z_taps_crest', 'gyro1Vec_taps_min', 'gyro1Vec_taps_max',
                       'gyro1Vec_taps_avg', 'gyro1Vec_taps_rms', 'gyro1Vec_taps_crest', 'gyro2x_taps_min',
                       'gyro2x_taps_max', 'gyro2x_taps_avg', 'gyro2x_taps_rms', 'gyro2x_taps_crest', 'gyro2y_taps_min',
                       'gyro2y_taps_max', 'gyro2y_taps_avg', 'gyro2y_taps_rms', 'gyro2y_taps_crest', 'gyro2z_taps_min',
                       'gyro2z_taps_max', 'gyro2z_taps_avg', 'gyro2z_taps_rms', 'gyro2z_taps_crest',
                       'gyro2Vec_taps_min', 'gyro2Vec_taps_max', 'gyro2Vec_taps_avg', 'gyro2Vec_taps_rms',
                       'gyro2Vec_taps_crest', 'gyro1x_max_val', 'gyro1x_max_frequency', 'gyro1x_delta_frequency',
                       'gyro1x_median_frequency', 'gyro1x_median_pow', 'gyro1x_frequency_ratio',
                       'gyro1x_median_frequency1', 'gyro1x_median_frequency2', 'gyro1x_dc_value', 'gyro1y_max_val',
                       'gyro1y_max_frequency', 'gyro1y_delta_frequency', 'gyro1y_median_frequency', 'gyro1y_median_pow',
                       'gyro1y_frequency_ratio', 'gyro1y_median_frequency1', 'gyro1y_median_frequency2',
                       'gyro1y_dc_value', 'gyro1z_max_val', 'gyro1z_max_frequency', 'gyro1z_delta_frequency',
                       'gyro1z_median_frequency', 'gyro1z_median_pow', 'gyro1z_frequency_ratio',
                       'gyro1z_median_frequency1', 'gyro1z_median_frequency2', 'gyro1z_dc_value', 'gyro1Vec_max_val',
                       'gyro1Vec_max_frequency', 'gyro1Vec_delta_frequency', 'gyro1Vec_median_frequency',
                       'gyro1Vec_median_pow', 'gyro1Vec_frequency_ratio', 'gyro1Vec_median_frequency1',
                       'gyro1Vec_median_frequency2', 'gyro1Vec_dc_value', 'gyro2x_max_val', 'gyro2x_max_frequency',
                       'gyro2x_delta_frequency', 'gyro2x_median_frequency', 'gyro2x_median_pow',
                       'gyro2x_median_frequency1', 'gyro2x_median_frequency2', 'gyro2x_dc_value', 'gyro2y_max_val',
                       'gyro2y_max_frequency', 'gyro2y_delta_frequency', 'gyro2y_median_frequency', 'gyro2y_median_pow',
                       'gyro2y_frequency_ratio', 'gyro2y_median_frequency1', 'gyro2y_median_frequency2',
                       'gyro2y_dc_value', 'gyro2z_max_val', 'gyro2z_max_frequency', 'gyro2z_delta_frequency',
                       'gyro2z_median_frequency', 'gyro2z_median_pow', 'gyro2z_median_frequency1',
                       'gyro2z_median_frequency2', 'gyro2z_dc_value', 'gyro2Vec_max_val', 'gyro2Vec_max_frequency',
                       'gyro2Vec_delta_frequency', 'gyro2Vec_median_pow', 'gyro2Vec_frequency_ratio',
                       'gyro2Vec_median_frequency1', 'gyro2Vec_median_frequency2', 'gyro2Vec_dc_value',
                       'gyro1x_max_speed_min', 'gyro1x_max_speed_max', 'gyro1x_max_speed_avg', 'gyro1x_max_speed_rms',
                       'gyro1x_max_speed_crest', 'gyro1y_max_speed_min', 'gyro1y_max_speed_max', 'gyro1y_max_speed_avg',
                       'gyro1y_max_speed_rms', 'gyro1y_max_speed_crest', 'gyro1z_max_speed_min', 'gyro1z_max_speed_max',
                       'gyro1z_max_speed_avg', 'gyro1z_max_speed_rms', 'gyro1z_max_speed_crest',
                       'gyro1Vec_max_speed_min', 'gyro1Vec_max_speed_max', 'gyro1Vec_max_speed_avg',
                       'gyro1Vec_max_speed_rms', 'gyro1Vec_max_speed_crest', 'gyro2x_max_speed_min',
                       'gyro2x_max_speed_max', 'gyro2x_max_speed_avg', 'gyro2x_max_speed_rms', 'gyro2x_max_speed_crest',
                       'gyro2y_max_speed_min', 'gyro2y_max_speed_max', 'gyro2y_max_speed_avg', 'gyro2y_max_speed_rms',
                       'gyro2y_max_speed_crest', 'gyro2z_max_speed_min', 'gyro2z_max_speed_max', 'gyro2z_max_speed_avg',
                       'gyro2z_max_speed_rms', 'gyro2z_max_speed_crest', 'gyro2Vec_max_speed_min',
                       'gyro2Vec_max_speed_max', 'gyro2Vec_max_speed_avg', 'gyro2Vec_max_speed_rms',
                       'gyro2Vec_max_speed_crest', 'gyro1x_max_acc_min', 'gyro1x_max_acc_max', 'gyro1x_max_acc_avg',
                       'gyro1x_max_acc_rms', 'gyro1x_max_acc_crest', 'gyro1y_max_acc_min', 'gyro1y_max_acc_max',
                       'gyro1y_max_acc_avg', 'gyro1y_max_acc_rms', 'gyro1y_max_acc_crest', 'gyro1z_max_acc_min',
                       'gyro1z_max_acc_max', 'gyro1z_max_acc_avg', 'gyro1z_max_acc_rms', 'gyro1z_max_acc_crest',
                       'gyro1Vec_max_acc_min', 'gyro1Vec_max_acc_max', 'gyro1Vec_max_acc_avg', 'gyro1Vec_max_acc_rms',
                       'gyro1Vec_max_acc_crest', 'gyro2x_max_acc_min', 'gyro2x_max_acc_max', 'gyro2x_max_acc_avg',
                       'gyro2x_max_acc_rms', 'gyro2x_max_acc_crest', 'gyro2y_max_acc_min', 'gyro2y_max_acc_max',
                       'gyro2y_max_acc_avg', 'gyro2y_max_acc_rms', 'gyro2y_max_acc_crest', 'gyro2z_max_acc_min',
                       'gyro2z_max_acc_max', 'gyro2z_max_acc_avg', 'gyro2z_max_acc_rms', 'gyro2z_max_acc_crest',
                       'gyro2Vec_max_acc_min', 'gyro2Vec_max_acc_max', 'gyro2Vec_max_acc_avg', 'gyro2Vec_max_acc_rms',
                       'gyro2Vec_max_acc_crest', 'gyro1x_max_power_min', 'gyro1x_max_power_max', 'gyro1x_max_power_avg',
                       'gyro1x_max_power_rms', 'gyro1x_max_power_crest', 'gyro1y_max_power_min', 'gyro1y_max_power_max',
                       'gyro1y_max_power_avg', 'gyro1y_max_power_rms', 'gyro1y_max_power_crest', 'gyro1z_max_power_min',
                       'gyro1z_max_power_max', 'gyro1z_max_power_avg', 'gyro1z_max_power_rms', 'gyro1z_max_power_crest',
                       'gyro1Vec_max_power_min', 'gyro1Vec_max_power_max', 'gyro1Vec_max_power_avg',
                       'gyro1Vec_max_power_rms', 'gyro1Vec_max_power_crest', 'gyro2x_max_power_min',
                       'gyro2x_max_power_max', 'gyro2x_max_power_avg', 'gyro2x_max_power_rms', 'gyro2x_max_power_crest',
                       'gyro2y_max_power_min', 'gyro2y_max_power_max', 'gyro2y_max_power_avg', 'gyro2y_max_power_rms',
                       'gyro2y_max_power_crest', 'gyro2z_max_power_min', 'gyro2z_max_power_max', 'gyro2z_max_power_avg',
                       'gyro2z_max_power_rms', 'gyro2z_max_power_crest', 'gyro2Vec_max_power_min',
                       'gyro2Vec_max_power_max', 'gyro2Vec_max_power_avg', 'gyro2Vec_max_power_rms',
                       'gyro2Vec_max_power_crest']

used_artefacts_mix7 = ['gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2Vec_max_angle_crest',
                       'gyro2Vec_median_frequency', 'gyro1Vec_median_frequency', 'gyro1Vec_median_frequency2',
                       'gyro1x_max_power_min', 'gyro1x_median_frequency', 'gyro1x_power_avg', 'gyro1x_power_crest',
                       'gyro1y_frequency_ratio', 'gyro1z_max_acc_min', 'gyro1z_max_acc_rms', 'gyro1z_median_frequency1',
                       'gyro1z_speed_crest', 'gyro1z_speed_rms', 'gyro2Vec_acc_rms', 'gyro2x_max_acc_min',
                       'gyro2x_power_crest', 'gyro2y_frequency_ratio', 'gyro2y_max_acc_crest',
                       'gyro2y_median_frequency1', 'gyro2z_max_power_crest', 'gyro1x_speed_std', 'gyro1x_max_speed_std',
                       'gyro1x_acc_std', 'gyro1x_max_acc_std', 'gyro1x_angle_std', 'gyro1x_max_angle_std',
                       'gyro1x_power_std', 'gyro1x_max_power_std', 'gyro1x_taps_std', 'gyro1y_speed_std',
                       'gyro1y_max_speed_std', 'gyro1y_acc_std', 'gyro1y_max_acc_std', 'gyro1y_angle_std',
                       'gyro1y_max_angle_std', 'gyro1y_power_std', 'gyro1y_max_power_std', 'gyro1y_taps_std',
                       'gyro1z_speed_std', 'gyro1z_max_speed_std', 'gyro1z_acc_std', 'gyro1z_max_acc_std',
                       'gyro1z_angle_std', 'gyro1z_max_angle_std', 'gyro1z_power_std', 'gyro1z_max_power_std',
                       'gyro1z_taps_std', 'gyro1Vec_speed_std', 'gyro1Vec_max_speed_std', 'gyro1Vec_acc_std',
                       'gyro1Vec_max_acc_std', 'gyro1Vec_angle_std', 'gyro1Vec_max_angle_std', 'gyro1Vec_power_std',
                       'gyro1Vec_max_power_std', 'gyro1Vec_taps_std', 'gyro2x_speed_std', 'gyro2x_max_speed_std',
                       'gyro2x_acc_std', 'gyro2x_max_acc_std', 'gyro2x_angle_std', 'gyro2x_max_angle_std',
                       'gyro2x_power_std', 'gyro2x_max_power_std', 'gyro2x_taps_std', 'gyro2y_speed_std',
                       'gyro2y_max_speed_std', 'gyro2y_acc_std', 'gyro2y_max_acc_std', 'gyro2y_angle_std',
                       'gyro2y_max_angle_std', 'gyro2y_power_std', 'gyro2y_max_power_std', 'gyro2y_taps_std',
                       'gyro2z_speed_std', 'gyro2z_max_speed_std', 'gyro2z_acc_std', 'gyro2z_max_acc_std',
                       'gyro2z_angle_std', 'gyro2z_max_angle_std', 'gyro2z_power_std', 'gyro2z_max_power_std',
                       'gyro2z_taps_std', 'gyro2Vec_speed_std', 'gyro2Vec_max_speed_std', 'gyro2Vec_acc_std',
                       'gyro2Vec_max_acc_std', 'gyro2Vec_angle_std', 'gyro2Vec_max_angle_std', 'gyro2Vec_power_std',
                       'gyro2Vec_max_power_std', 'gyro2Vec_taps_std']

used_artefacts_mix8 = ['gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2Vec_max_angle_crest',
                       'gyro2Vec_median_frequency', 'gyro2Vec_acc_rms', 'gyro2x_max_acc_min',
                       'gyro2y_median_frequency1']

used_artefacts_mix9 = ['gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2Vec_max_angle_crest',
                       'gyro2Vec_median_frequency', 'gyro2Vec_acc_rms', 'gyro2x_max_acc_min',
                       'gyro2y_median_frequency1', 'gyro2x_frequency_ratio1', 'gyro2z_frequency_ratio1']

used_artefacts_mix10 = ['gyro2Vec_speed_min', 'gyro2Vec_speed_max', 'gyro2Vec_speed_avg', 'gyro2Vec_speed_rms',
                        'gyro2Vec_speed_crest', 'gyro2Vec_speed_std', 'gyro2Vec_acc_min', 'gyro2Vec_acc_max',
                        'gyro2Vec_acc_avg', 'gyro2Vec_acc_rms', 'gyro2Vec_acc_crest', 'gyro2Vec_acc_std',
                        'gyro2Vec_angle_min', 'gyro2Vec_angle_max', 'gyro2Vec_angle_avg', 'gyro2Vec_angle_rms',
                        'gyro2Vec_angle_crest', 'gyro2Vec_angle_std', 'gyro2Vec_power_min', 'gyro2Vec_power_max',
                        'gyro2Vec_power_avg', 'gyro2Vec_power_rms', 'gyro2Vec_power_crest', 'gyro2Vec_power_std',
                        'gyro2Vec_taps_min', 'gyro2Vec_taps_max', 'gyro2Vec_taps_avg', 'gyro2Vec_taps_rms',
                        'gyro2Vec_taps_crest', 'gyro2Vec_taps_std', 'gyro2Vec_max_val', 'gyro2Vec_max_frequency',
                        'gyro2Vec_delta_frequency', 'gyro2Vec_median_frequency', 'gyro2Vec_median_pow',
                        'gyro2Vec_frequency_ratio', 'gyro2Vec_median_frequency1', 'gyro2Vec_median_frequency2',
                        'gyro2Vec_dc_value', 'gyro2Vec_frequency_ratio1', 'gyro2Vec_max_speed_min',
                        'gyro2Vec_max_speed_max', 'gyro2Vec_max_speed_avg', 'gyro2Vec_max_speed_rms',
                        'gyro2Vec_max_speed_crest', 'gyro2Vec_max_speed_std', 'gyro2Vec_max_acc_min',
                        'gyro2Vec_max_acc_max', 'gyro2Vec_max_acc_avg', 'gyro2Vec_max_acc_rms',
                        'gyro2Vec_max_acc_crest', 'gyro2Vec_max_acc_std', 'gyro2Vec_max_angle_min',
                        'gyro2Vec_max_angle_max', 'gyro2Vec_max_angle_avg', 'gyro2Vec_max_angle_rms',
                        'gyro2Vec_max_angle_crest', 'gyro2Vec_max_angle_std', 'gyro2Vec_max_power_min',
                        'gyro2Vec_max_power_max', 'gyro2Vec_max_power_avg', 'gyro2Vec_max_power_rms',
                        'gyro2Vec_max_power_crest', 'gyro2Vec_max_power_std']

used_artefacts_mix11 = ['gyro2Vec_speed_min', 'gyro2Vec_frequency_ratio', 'gyro2Vec_max_angle_crest',
                        'gyro2Vec_speed_max', 'gyro2Vec_speed_avg', 'gyro2Vec_speed_rms', 'gyro2Vec_speed_crest',
                        'gyro2Vec_speed_std', 'gyro2Vec_acc_min', 'gyro2Vec_acc_max', 'gyro2Vec_acc_avg',
                        'gyro2Vec_acc_rms', 'gyro2Vec_acc_crest', 'gyro2Vec_acc_std', 'gyro2Vec_angle_min',
                        'gyro2Vec_angle_max', 'gyro2Vec_angle_avg', 'gyro2Vec_angle_rms', 'gyro2Vec_angle_crest',
                        'gyro2Vec_angle_std', 'gyro2Vec_power_min', 'gyro2Vec_power_max', 'gyro2Vec_power_avg',
                        'gyro2Vec_power_rms', 'gyro2Vec_power_crest', 'gyro2Vec_power_std', 'gyro2Vec_taps_min',
                        'gyro2Vec_taps_max', 'gyro2Vec_taps_avg', 'gyro2Vec_taps_rms', 'gyro2Vec_taps_crest',
                        'gyro2Vec_taps_std', 'gyro2Vec_max_val', 'gyro2Vec_max_frequency', 'gyro2Vec_delta_frequency',
                        'gyro2Vec_median_frequency', 'gyro2Vec_median_pow', 'gyro2Vec_median_frequency1',
                        'gyro2Vec_median_frequency2', 'gyro2Vec_dc_value', 'gyro2Vec_frequency_ratio1',
                        'gyro2Vec_max_speed_min', 'gyro2Vec_max_speed_max', 'gyro2Vec_max_speed_avg',
                        'gyro2Vec_max_speed_rms', 'gyro2Vec_max_speed_crest', 'gyro2Vec_max_speed_std',
                        'gyro2Vec_max_acc_min', 'gyro2Vec_max_acc_max', 'gyro2Vec_max_acc_avg', 'gyro2Vec_max_acc_rms',
                        'gyro2Vec_max_acc_crest', 'gyro2Vec_max_acc_std', 'gyro2Vec_max_angle_min',
                        'gyro2Vec_max_angle_max', 'gyro2Vec_max_angle_avg', 'gyro2Vec_max_angle_rms',
                        'gyro2Vec_max_angle_std', 'gyro2Vec_max_power_min', 'gyro2Vec_max_power_max',
                        'gyro2Vec_max_power_avg', 'gyro2Vec_max_power_rms', 'gyro2Vec_max_power_crest',
                        'gyro2Vec_max_power_std']

used_artefacts_mix12 = ['gyro2Vec_speed_min', 'gyro2Vec_frequency_ratio', 'gyro2Vec_max_angle_crest',
                        'gyro2Vec_angle_crest', 'gyro2Vec_median_frequency', 'gyro2Vec_max_angle_min',
                        'gyro2Vec_taps_min', 'gyro2Vec_median_frequency2', 'gyro2Vec_power_min', 'gyro2Vec_taps_crest']

used_artefacts_mix13 = ['gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2Vec_median_frequency',
                        'gyro2Vec_max_angle_crest', 'gyro2Vec_max_angle_std', 'gyro2x_max_acc_min',
                        'gyro2z_max_acc_min', 'gyro2x_frequency_ratio1', 'gyro2z_frequency_ratio1',
                        'gyro2y_median_frequency1', 'gyro2y_median_frequency2', 'gyro2Vec_speed_std',
                        'gyro2Vec_acc_crest', 'gyro2Vec_acc_rms', 'gyro2Vec_acc_std', 'gyro2Vec_power_rms',
                        'gyro2Vec_power_std']

used_artefacts_mix14 = ['gyro2Vec_acc_crest', 'gyro2Vec_acc_rms', 'gyro2Vec_acc_std', 'gyro2Vec_median_frequency',
                        'gyro2Vec_power_std', 'gyro2Vec_speed_std', 'gyro2x_frequency_ratio', 'gyro2x_max_acc_min']

used_artefacts_mix15 = ['gyro1Vec_max_power_crest', 'gyro1Vec_median_frequency2', 'gyro1Vec_speed_rms',
                        'gyro1x_max_acc_crest', 'gyro1x_max_angle_max', 'gyro1x_max_angle_rms',
                        'gyro1x_max_power_crest', 'gyro1x_max_speed_avg', 'gyro1x_max_speed_max', 'gyro1x_power_avg',
                        'gyro1x_speed_max', 'gyro1x_speed_rms', 'gyro1x_taps_max', 'gyro1y_frequency_ratio',
                        'gyro1y_max_power_crest', 'gyro1y_median_frequency', 'gyro1y_median_frequency2',
                        'gyro1y_power_min', 'gyro1z_frequency_ratio', 'gyro1z_max_power_avg', 'gyro1z_median_pow',
                        'gyro1z_speed_crest', 'gyro1z_taps_crest', 'gyro2Vec_acc_max', 'gyro2Vec_frequency_ratio',
                        'gyro2Vec_max_acc_avg', 'gyro2Vec_max_angle_crest', 'gyro2Vec_max_angle_min',
                        'gyro2Vec_max_speed_crest', 'gyro2Vec_median_frequency', 'gyro2Vec_median_frequency1',
                        'gyro2Vec_median_frequency2', 'gyro2Vec_speed_avg', 'gyro2Vec_taps_max', 'gyro2Vec_taps_rms',
                        'gyro2x_frequency_ratio', 'gyro2x_max_acc_min', 'gyro2x_max_angle_crest',
                        'gyro2x_max_angle_max', 'gyro2x_max_power_max', 'gyro2x_median_pow', 'gyro2x_power_avg',
                        'gyro2x_power_rms', 'gyro2x_speed_rms', 'gyro2x_taps_min', 'gyro2y_acc_rms',
                        'gyro2y_max_angle_crest', 'gyro2y_max_speed_crest', 'gyro2y_max_speed_max', 'gyro2y_power_avg',
                        'gyro2y_taps_crest', 'gyro2z_frequency_ratio', 'gyro2z_max_speed_max', 'gyro2z_power_min',
                        'gyro2z_taps_max']

used_artefacts_mix16 = ['gyro1y_frequency_ratio', 'gyro2Vec_max_angle_crest', 'gyro2x_frequency_ratio',
                        'gyro2y_acc_rms', 'gyro2y_max_angle_crest', 'gyro2z_frequency_ratio', 'gyro2z_max_power_crest',

                        'gyro2Vec_median_frequency', 'gyro1x_speed_min', 'gyro1x_speed_max', 'gyro1x_speed_avg',
                        'gyro1x_speed_rms', 'gyro1x_speed_crest', 'gyro1y_speed_min', 'gyro1y_speed_max',
                        'gyro1y_speed_avg', 'gyro1y_speed_rms', 'gyro1y_speed_crest', 'gyro1z_speed_min',
                        'gyro1z_speed_max', 'gyro1z_speed_avg', 'gyro1z_speed_rms', 'gyro1z_speed_crest',
                        'gyro1Vec_speed_min', 'gyro1Vec_speed_max', 'gyro1Vec_speed_avg', 'gyro1Vec_speed_rms',
                        'gyro1Vec_speed_crest', 'gyro2x_speed_min', 'gyro2x_speed_max', 'gyro2x_speed_avg',
                        'gyro2x_speed_rms', 'gyro2x_speed_crest', 'gyro2y_speed_min', 'gyro2y_speed_max',
                        'gyro2y_speed_avg', 'gyro2y_speed_rms', 'gyro2y_speed_crest', 'gyro2z_speed_min',
                        'gyro2z_speed_max', 'gyro2z_speed_avg', 'gyro2z_speed_rms', 'gyro2z_speed_crest',
                        'gyro2Vec_speed_min', 'gyro2Vec_speed_max', 'gyro2Vec_speed_avg', 'gyro2Vec_speed_rms',
                        'gyro2Vec_speed_crest', 'gyro1x_acc_min', 'gyro1x_acc_max', 'gyro1x_acc_avg', 'gyro1x_acc_rms',
                        'gyro1x_acc_crest', 'gyro1y_acc_min', 'gyro1y_acc_max', 'gyro1y_acc_avg', 'gyro1y_acc_rms',
                        'gyro1y_acc_crest', 'gyro1z_acc_min', 'gyro1z_acc_max', 'gyro1z_acc_avg', 'gyro1z_acc_rms',
                        'gyro1z_acc_crest', 'gyro1Vec_acc_min', 'gyro1Vec_acc_max', 'gyro1Vec_acc_avg',
                        'gyro1Vec_acc_rms', 'gyro1Vec_acc_crest', 'gyro2x_acc_min', 'gyro2x_acc_max', 'gyro2x_acc_avg',
                        'gyro2x_acc_rms', 'gyro2x_acc_crest', 'gyro2y_acc_min', 'gyro2y_acc_max', 'gyro2y_acc_avg',
                        'gyro2y_acc_crest', 'gyro2z_acc_min', 'gyro2z_acc_max', 'gyro2z_acc_avg',
                        'gyro2z_acc_rms', 'gyro2z_acc_crest', 'gyro2Vec_acc_min', 'gyro2Vec_acc_max',
                        'gyro2Vec_acc_avg',
                        'gyro2Vec_acc_rms', 'gyro2Vec_acc_crest', 'gyro1x_max_angle_min', 'gyro1x_max_angle_max',
                        'gyro1x_max_angle_avg', 'gyro1x_max_angle_rms', 'gyro1x_max_angle_crest',
                        'gyro1y_max_angle_min',
                        'gyro1y_max_angle_max', 'gyro1y_max_angle_avg', 'gyro1y_max_angle_rms',
                        'gyro1y_max_angle_crest',
                        'gyro1z_max_angle_min', 'gyro1z_max_angle_max', 'gyro1z_max_angle_avg', 'gyro1z_max_angle_rms',
                        'gyro1z_max_angle_crest', 'gyro1Vec_max_angle_min', 'gyro1Vec_max_angle_max',
                        'gyro1Vec_max_angle_avg', 'gyro1Vec_max_angle_rms', 'gyro1Vec_max_angle_crest',
                        'gyro2x_max_angle_min', 'gyro2x_max_angle_max', 'gyro2x_max_angle_avg', 'gyro2x_max_angle_rms',
                        'gyro2x_max_angle_crest', 'gyro2y_max_angle_min', 'gyro2y_max_angle_max',
                        'gyro2y_max_angle_avg',
                        'gyro2y_max_angle_rms', 'gyro2z_max_angle_min', 'gyro2z_max_angle_max',
                        'gyro2z_max_angle_avg', 'gyro2z_max_angle_rms', 'gyro2z_max_angle_crest',
                        'gyro2Vec_max_angle_min', 'gyro2Vec_max_angle_max', 'gyro2Vec_max_angle_avg',
                        'gyro2Vec_max_angle_rms', 'gyro1x_power_min', 'gyro1x_power_max', 'gyro1x_power_avg',
                        'gyro1x_power_rms', 'gyro1x_power_crest', 'gyro1y_power_min', 'gyro1y_power_max',
                        'gyro1y_power_avg', 'gyro1y_power_rms', 'gyro1y_power_crest', 'gyro1z_power_min',
                        'gyro1z_power_max', 'gyro1z_power_avg', 'gyro1z_power_rms', 'gyro1z_power_crest',
                        'gyro1Vec_power_min', 'gyro1Vec_power_max', 'gyro1Vec_power_avg', 'gyro1Vec_power_rms',
                        'gyro1Vec_power_crest', 'gyro2x_power_min', 'gyro2x_power_max', 'gyro2x_power_avg',
                        'gyro2x_power_rms', 'gyro2x_power_crest', 'gyro2y_power_min', 'gyro2y_power_max',
                        'gyro2y_power_avg', 'gyro2y_power_rms', 'gyro2y_power_crest', 'gyro2z_power_min',
                        'gyro2z_power_max', 'gyro2z_power_avg', 'gyro2z_power_rms', 'gyro2z_power_crest',
                        'gyro2Vec_power_min', 'gyro2Vec_power_max', 'gyro2Vec_power_avg', 'gyro2Vec_power_rms',
                        'gyro2Vec_power_crest', 'gyro1x_taps_min', 'gyro1x_taps_max', 'gyro1x_taps_avg',
                        'gyro1x_taps_rms', 'gyro1x_taps_crest', 'gyro1y_taps_min', 'gyro1y_taps_max', 'gyro1y_taps_avg',
                        'gyro1y_taps_rms', 'gyro1y_taps_crest', 'gyro1z_taps_min', 'gyro1z_taps_max', 'gyro1z_taps_avg',
                        'gyro1z_taps_rms', 'gyro1z_taps_crest', 'gyro1Vec_taps_min', 'gyro1Vec_taps_max',
                        'gyro1Vec_taps_avg', 'gyro1Vec_taps_rms', 'gyro1Vec_taps_crest', 'gyro2x_taps_min',
                        'gyro2x_taps_max', 'gyro2x_taps_avg', 'gyro2x_taps_rms', 'gyro2x_taps_crest', 'gyro2y_taps_min',
                        'gyro2y_taps_max', 'gyro2y_taps_avg', 'gyro2y_taps_rms', 'gyro2y_taps_crest', 'gyro2z_taps_min',
                        'gyro2z_taps_max', 'gyro2z_taps_avg', 'gyro2z_taps_rms', 'gyro2z_taps_crest',
                        'gyro2Vec_taps_min', 'gyro2Vec_taps_max', 'gyro2Vec_taps_avg', 'gyro2Vec_taps_rms',
                        'gyro2Vec_taps_crest', 'gyro1x_max_val', 'gyro1x_max_frequency', 'gyro1x_delta_frequency',
                        'gyro1x_median_frequency', 'gyro1x_median_pow', 'gyro1x_frequency_ratio',
                        'gyro1x_median_frequency1', 'gyro1x_median_frequency2', 'gyro1x_dc_value', 'gyro1y_max_val',
                        'gyro1y_max_frequency', 'gyro1y_delta_frequency', 'gyro1y_median_frequency',
                        'gyro1y_median_pow',
                        'gyro1y_median_frequency1', 'gyro1y_median_frequency2',
                        'gyro1y_dc_value', 'gyro1z_max_val', 'gyro1z_max_frequency', 'gyro1z_delta_frequency',
                        'gyro1z_median_frequency', 'gyro1z_median_pow', 'gyro1z_frequency_ratio',
                        'gyro1z_median_frequency1', 'gyro1z_median_frequency2', 'gyro1z_dc_value', 'gyro1Vec_max_val',
                        'gyro1Vec_max_frequency', 'gyro1Vec_delta_frequency', 'gyro1Vec_median_frequency',
                        'gyro1Vec_median_pow', 'gyro1Vec_frequency_ratio', 'gyro1Vec_median_frequency1',
                        'gyro1Vec_median_frequency2', 'gyro1Vec_dc_value', 'gyro2x_max_val', 'gyro2x_max_frequency',
                        'gyro2x_delta_frequency', 'gyro2x_median_frequency', 'gyro2x_median_pow',
                        'gyro2x_median_frequency1', 'gyro2x_median_frequency2', 'gyro2x_dc_value', 'gyro2y_max_val',
                        'gyro2y_max_frequency', 'gyro2y_delta_frequency', 'gyro2y_median_frequency',
                        'gyro2y_median_pow',
                        'gyro2y_frequency_ratio', 'gyro2y_median_frequency1', 'gyro2y_median_frequency2',
                        'gyro2y_dc_value', 'gyro2z_max_val', 'gyro2z_max_frequency', 'gyro2z_delta_frequency',
                        'gyro2z_median_frequency', 'gyro2z_median_pow', 'gyro2z_median_frequency1',
                        'gyro2z_median_frequency2', 'gyro2z_dc_value', 'gyro2Vec_max_val', 'gyro2Vec_max_frequency',
                        'gyro2Vec_delta_frequency', 'gyro2Vec_median_pow', 'gyro2Vec_frequency_ratio',
                        'gyro2Vec_median_frequency1', 'gyro2Vec_median_frequency2', 'gyro2Vec_dc_value',
                        'gyro1x_max_speed_min', 'gyro1x_max_speed_max', 'gyro1x_max_speed_avg', 'gyro1x_max_speed_rms',
                        'gyro1x_max_speed_crest', 'gyro1y_max_speed_min', 'gyro1y_max_speed_max',
                        'gyro1y_max_speed_avg',
                        'gyro1y_max_speed_rms', 'gyro1y_max_speed_crest', 'gyro1z_max_speed_min',
                        'gyro1z_max_speed_max',
                        'gyro1z_max_speed_avg', 'gyro1z_max_speed_rms', 'gyro1z_max_speed_crest',
                        'gyro1Vec_max_speed_min', 'gyro1Vec_max_speed_max', 'gyro1Vec_max_speed_avg',
                        'gyro1Vec_max_speed_rms', 'gyro1Vec_max_speed_crest', 'gyro2x_max_speed_min',
                        'gyro2x_max_speed_max', 'gyro2x_max_speed_avg', 'gyro2x_max_speed_rms',
                        'gyro2x_max_speed_crest',
                        'gyro2y_max_speed_min', 'gyro2y_max_speed_max', 'gyro2y_max_speed_avg', 'gyro2y_max_speed_rms',
                        'gyro2y_max_speed_crest', 'gyro2z_max_speed_min', 'gyro2z_max_speed_max',
                        'gyro2z_max_speed_avg',
                        'gyro2z_max_speed_rms', 'gyro2z_max_speed_crest', 'gyro2Vec_max_speed_min',
                        'gyro2Vec_max_speed_max', 'gyro2Vec_max_speed_avg', 'gyro2Vec_max_speed_rms',
                        'gyro2Vec_max_speed_crest', 'gyro1x_max_acc_min', 'gyro1x_max_acc_max', 'gyro1x_max_acc_avg',
                        'gyro1x_max_acc_rms', 'gyro1x_max_acc_crest', 'gyro1y_max_acc_min', 'gyro1y_max_acc_max',
                        'gyro1y_max_acc_avg', 'gyro1y_max_acc_rms', 'gyro1y_max_acc_crest', 'gyro1z_max_acc_min',
                        'gyro1z_max_acc_max', 'gyro1z_max_acc_avg', 'gyro1z_max_acc_rms', 'gyro1z_max_acc_crest',
                        'gyro1Vec_max_acc_min', 'gyro1Vec_max_acc_max', 'gyro1Vec_max_acc_avg', 'gyro1Vec_max_acc_rms',
                        'gyro1Vec_max_acc_crest', 'gyro2x_max_acc_min', 'gyro2x_max_acc_max', 'gyro2x_max_acc_avg',
                        'gyro2x_max_acc_rms', 'gyro2x_max_acc_crest', 'gyro2y_max_acc_min', 'gyro2y_max_acc_max',
                        'gyro2y_max_acc_avg', 'gyro2y_max_acc_rms', 'gyro2y_max_acc_crest', 'gyro2z_max_acc_min',
                        'gyro2z_max_acc_max', 'gyro2z_max_acc_avg', 'gyro2z_max_acc_rms', 'gyro2z_max_acc_crest',
                        'gyro2Vec_max_acc_min', 'gyro2Vec_max_acc_max', 'gyro2Vec_max_acc_avg', 'gyro2Vec_max_acc_rms',
                        'gyro2Vec_max_acc_crest', 'gyro1x_max_power_min', 'gyro1x_max_power_max',
                        'gyro1x_max_power_avg',
                        'gyro1x_max_power_rms', 'gyro1x_max_power_crest', 'gyro1y_max_power_min',
                        'gyro1y_max_power_max',
                        'gyro1y_max_power_avg', 'gyro1y_max_power_rms', 'gyro1y_max_power_crest',
                        'gyro1z_max_power_min',
                        'gyro1z_max_power_max', 'gyro1z_max_power_avg', 'gyro1z_max_power_rms',
                        'gyro1z_max_power_crest',
                        'gyro1Vec_max_power_min', 'gyro1Vec_max_power_max', 'gyro1Vec_max_power_avg',
                        'gyro1Vec_max_power_rms', 'gyro1Vec_max_power_crest', 'gyro2x_max_power_min',
                        'gyro2x_max_power_max', 'gyro2x_max_power_avg', 'gyro2x_max_power_rms',
                        'gyro2x_max_power_crest',
                        'gyro2y_max_power_min', 'gyro2y_max_power_max', 'gyro2y_max_power_avg', 'gyro2y_max_power_rms',
                        'gyro2y_max_power_crest', 'gyro2z_max_power_min', 'gyro2z_max_power_max',
                        'gyro2z_max_power_avg',
                        'gyro2z_max_power_rms', 'gyro2Vec_max_power_min',
                        'gyro2Vec_max_power_max', 'gyro2Vec_max_power_avg', 'gyro2Vec_max_power_rms',
                        'gyro2Vec_max_power_crest']

used_artefacts_mix17 = ['gyro1y_frequency_ratio', 'gyro2Vec_max_angle_crest', 'gyro2x_frequency_ratio',
                        'gyro2y_acc_rms', 'gyro2y_max_angle_crest', 'gyro2z_frequency_ratio', 'gyro2z_max_power_crest',

                        'gyro1Vec_acc_avg', 'gyro1Vec_max_acc_min', 'gyro1Vec_max_frequency',
                        'gyro1Vec_max_speed_crest', 'gyro1Vec_median_frequency', 'gyro1Vec_median_frequency1',
                        'gyro1Vec_median_frequency2', 'gyro1Vec_power_min', 'gyro1Vec_speed_min', 'gyro1x_acc_avg',
                        'gyro1x_acc_rms', 'gyro1x_max_acc_min', 'gyro1x_max_frequency', 'gyro1x_power_min',
                        'gyro1x_speed_avg', 'gyro1x_speed_rms', 'gyro1y_acc_avg', 'gyro1y_max_frequency',
                        'gyro1y_median_frequency', 'gyro1y_median_frequency1', 'gyro1y_median_frequency2',
                        'gyro1y_power_min', 'gyro1y_speed_avg', 'gyro1z_acc_avg', 'gyro1z_delta_frequency',
                        'gyro1z_max_frequency', 'gyro1z_median_frequency', 'gyro1z_median_frequency1',
                        'gyro1z_median_frequency2', 'gyro1z_power_min', 'gyro1z_speed_avg', 'gyro2Vec_acc_avg',
                        'gyro2Vec_max_frequency', 'gyro2Vec_max_speed_crest', 'gyro2Vec_median_frequency',
                        'gyro2Vec_median_frequency1', 'gyro2Vec_power_min', 'gyro2Vec_speed_min', 'gyro2x_acc_avg',
                        'gyro2x_delta_frequency', 'gyro2x_max_frequency', 'gyro2x_median_frequency2',
                        'gyro2x_power_min', 'gyro2x_speed_avg', 'gyro2y_acc_avg', 'gyro2y_delta_frequency',
                        'gyro2y_max_frequency', 'gyro2y_median_frequency', 'gyro2y_median_frequency1',
                        'gyro2y_power_min', 'gyro2y_speed_avg', 'gyro2z_acc_avg', 'gyro2z_delta_frequency',
                        'gyro2z_max_acc_crest', 'gyro2z_max_angle_crest', 'gyro2z_max_frequency',
                        'gyro2z_max_speed_crest', 'gyro2z_median_frequency', 'gyro2z_median_frequency1',
                        'gyro2z_power_min']

used_artefacts_mix18 = ['gyro1y_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro2z_frequency_ratio',
                        'gyro2Vec_max_angle_crest', 'gyro2y_acc_rms', 'gyro2y_max_angle_crest',
                        'gyro2z_max_power_crest',
                        'gyro1Vec_median_frequency1', 'gyro1Vec_power_min', 'gyro1Vec_speed_min',
                        'gyro1x_acc_avg', 'gyro1x_max_frequency', 'gyro1x_power_min', 'gyro1x_speed_avg',
                        'gyro1x_speed_rms', 'gyro1y_acc_avg', 'gyro1y_max_frequency', 'gyro1y_median_frequency',
                        'gyro1y_median_frequency1', 'gyro1y_power_min', 'gyro1y_speed_avg', 'gyro1z_acc_avg',
                        'gyro1z_delta_frequency', 'gyro1z_max_frequency', 'gyro1z_median_frequency1',
                        'gyro1z_median_frequency2', 'gyro1z_power_min', 'gyro2Vec_acc_avg', 'gyro2Vec_max_frequency',
                        'gyro2Vec_median_frequency', 'gyro2Vec_median_frequency1', 'gyro2Vec_power_min',
                        'gyro2Vec_speed_min', 'gyro2x_acc_avg', 'gyro2x_delta_frequency', 'gyro2x_max_frequency',
                        'gyro2x_power_min', 'gyro2x_speed_avg', 'gyro2y_acc_avg', 'gyro2y_delta_frequency',
                        'gyro2y_max_frequency', 'gyro2y_median_frequency', 'gyro2y_median_frequency1',
                        'gyro2y_power_min', 'gyro2y_speed_avg', 'gyro2z_acc_avg', 'gyro2z_max_acc_crest',
                        'gyro2z_max_frequency', 'gyro2z_median_frequency1', 'gyro2z_power_min']

used_artefacts_mix19 = ['gyro1y_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro2z_frequency_ratio',
                        'gyro2Vec_max_angle_crest', 'gyro2y_acc_rms', 'gyro2y_max_angle_crest',
                        'gyro2z_max_power_crest', 'gyro1x_speed_rms', 'gyro2Vec_speed_min', 'gyro2y_delta_frequency',
                        'gyro2z_max_acc_crest', 'gyro2x_delta_frequency']

used_artefacts_mix20 = ['gyro1y_frequency_ratio', 'gyro2x_frequency_ratio', 'gyro2z_frequency_ratio', 'gyro2y_acc_rms',
                        'gyro2y_max_angle_crest', 'gyro2z_max_power_crest', 'gyro2Vec_max_angle_crest',
                        'gyro2Vec_speed_min', 'gyro1x_speed_rms', 'gyro2y_delta_frequency', 'gyro2z_max_acc_crest',
                        'gyro2y_max_power_crest', 'gyro2y_frequency_ratio', 'gyro2y_speed_min', 'gyro2y_speed_rms',
                        'gyro2y_max_acc_crest']

used_artefacts_mix21 = ['gyro1Vec_speed_min', 'gyro1x_power_min', 'gyro1z_max_acc_avg', 'gyro1z_power_min',
                        'gyro2Vec_max_power_min', 'gyro2Vec_median_frequency', 'gyro2x_dc_value', 'gyro2x_power_min',
                        'gyro2x_power_rms', 'gyro2y_acc_min', 'gyro2y_max_power_rms']

used_artefacts_mix22 = ['gyro1Vec_frequency_ratio', 'gyro1Vec_max_angle_crest', 'gyro1Vec_power_min',
                        'gyro1Vec_speed_min', 'gyro1x_max_frequency', 'gyro1y_angle_crest', 'gyro1y_frequency_ratio',
                        'gyro1z_max_acc_std', 'gyro1z_max_power_avg', 'gyro1z_max_power_std', 'gyro2x_frequency_ratio1',
                        'gyro2x_power_min', 'gyro2y_acc_rms', 'gyro2y_max_speed_crest', 'gyro2y_max_speed_rms',
                        'gyro2y_median_frequency1', 'gyro2y_power_min', 'gyro2z_angle_rms', 'gyro2z_frequency_ratio',
                        'gyro2z_max_acc_std', 'gyro2z_power_min']

used_artefacts_mix23 = ['gyro2Vec_acc_min', 'gyro2x_power_avg', 'gyro1y_frequency_ratio', 'gyro1z_median_pow',
                        'gyro2y_median_pow', 'gyro2y_median_frequency1', 'gyro2y_max_speed_rms', 'gyro1z_max_acc_std',
                        'gyro2z_max_acc_std']

used_artefacts_mix24 = ['gyro1x_max_val', 'gyro1y_frequency_ratio', 'gyro1z_max_acc_std', 'gyro1z_max_speed_avg',
                        'gyro1z_max_speed_rms', 'gyro1z_median_pow', 'gyro2Vec_acc_min', 'gyro2Vec_max_speed_crest',
                        'gyro2x_power_avg', 'gyro2y_acc_rms', 'gyro2y_acc_std', 'gyro2y_max_speed_rms',
                        'gyro2y_median_frequency1', 'gyro2z_max_acc_std']

used_artefacts_mix25 = ['gyro1x_max_val', 'gyro1y_frequency_ratio', 'gyro1z_max_acc_std', 'gyro1z_max_speed_avg',
                        'gyro1z_max_speed_rms', 'gyro1z_median_pow', 'gyro2Vec_acc_min', 'gyro2Vec_max_speed_crest',
                        'gyro2x_power_avg', 'gyro2y_acc_rms', 'gyro2y_acc_std', 'gyro2y_max_speed_rms',
                        'gyro2y_median_frequency1', 'gyro2z_max_acc_std', 'gyro2x_frequency_ratio',
                        'gyro2z_frequency_ratio', 'gyro2Vec_max_angle_crest', 'gyro2Vec_median_frequency',
                        'gyro2Vec_acc_rms', 'gyro2x_max_acc_min']

used_artefacts_mix26 = ['gyro1x_max_frequency', 'gyro1x_max_val', 'gyro1z_max_acc_std', 'gyro1z_max_power_avg',
                        'gyro1z_max_power_rms', 'gyro1z_power_avg', 'gyro2Vec_median_frequency', 'gyro2x_power_avg',
                        'gyro2x_power_rms', 'gyro2x_power_std', 'gyro2y_acc_rms', 'gyro2y_acc_std',
                        'gyro2y_max_speed_avg', 'gyro2y_max_speed_rms']

used_artefacts_mix27 = ['gyro2y_acc_rms', 'gyro2x_power_avg', 'gyro1x_max_val', 'gyro2Vec_median_frequency',
                        'gyro2y_max_speed_avg', 'gyro1z_max_acc_std', 'gyro2y_acc_std', 'gyro1x_frequency_ratio',
                        'gyro1y_frequency_ratio', 'gyro1z_frequency_ratio', 'gyro1Vec_frequency_ratio',
                        'gyro2x_frequency_ratio', 'gyro2y_frequency_ratio', 'gyro2z_frequency_ratio',
                        'gyro2Vec_frequency_ratio', 'gyro1x_delta_frequency', 'gyro1y_delta_frequency',
                        'gyro1z_delta_frequency', 'gyro1Vec_delta_frequency', 'gyro2x_delta_frequency',
                        'gyro2y_delta_frequency', 'gyro2z_delta_frequency', 'gyro2Vec_delta_frequency']

used_artefacts_mix28 = ['gyro1x_max_speed_rms', 'gyro1x_max_power_min', 'gyro1y_frequency_ratio', 'gyro1y_max_acc_rms',
                        'gyro1z_speed_min', 'gyro1z_frequency_ratio1', 'gyro1Vec_speed_min', 'gyro1Vec_delta_frequency',
                        'gyro2x_frequency_ratio', 'gyro2x_max_power_min', 'gyro2y_acc_std', 'gyro2y_acc_rms',
                        'gyro2y_median_frequency', 'gyro2z_taps_rms', 'gyro2z_frequency_ratio',
                        'gyro2Vec_median_frequency2', 'gyro2Vec_max_speed_rms']

used_artefacts_mix29 = ['gyro2y_acc_rms', 'gyro2x_power_avg', 'gyro1x_max_val', 'gyro2Vec_median_frequency',
                        'gyro2y_max_speed_avg', 'gyro1z_max_acc_std']  # TODO trenutno najblja kombinacija sa 205 od 268

used_artefacts_mix30 = ['gyro2y_acc_rms', 'gyro2x_power_avg', 'gyro1x_max_val', 'gyro2Vec_median_frequency',
                        'gyro2y_max_speed_avg', 'gyro1z_max_acc_std',

                        'gyro1x_max_angle_angle', 'gyro1x_max_angle_area', 'gyro1y_max_angle_angle',
                        'gyro1y_max_angle_area', 'gyro1z_max_angle_angle', 'gyro1z_max_angle_area',
                        'gyro1Vec_max_angle_angle', 'gyro1Vec_max_angle_area', 'gyro2x_max_angle_angle',
                        'gyro2x_max_angle_area', 'gyro2y_max_angle_angle', 'gyro2y_max_angle_area',
                        'gyro2z_max_angle_angle', 'gyro2z_max_angle_area', 'gyro2Vec_max_angle_angle',
                        'gyro2Vec_max_angle_area']

used_artefacts_mix31 = ['gyro2y_acc_rms', 'gyro2x_power_avg', 'gyro1x_max_val', 'gyro2Vec_median_frequency',
                        'gyro2y_max_speed_avg', 'gyro1z_max_acc_std',

                        'gyro1y_max_acc_min', 'gyro1x_speed_rms', 'gyro1z_power_std', 'gyro1y_frequency_ratio1',
                        'gyro2y_median_frequency1', 'gyro1Vec_max_speed_crest', 'gyro2y_max_acc_avg',
                        'gyro2z_max_acc_area', 'gyro1y_max_power_angle']

used_artefacts_mix32 = ['gyro1x_speed_wangle_avg', 'gyro1x_speed_wangle_rms', 'gyro1x_speed_wangle_crest',
                        'gyro1x_speed_wangle_std', 'gyro1x_speed_warea_avg', 'gyro1x_speed_warea_rms',
                        'gyro1x_speed_warea_crest', 'gyro1x_speed_warea_std', 'gyro1y_speed_wangle_avg',
                        'gyro1y_speed_wangle_rms', 'gyro1y_speed_wangle_crest', 'gyro1y_speed_wangle_std',
                        'gyro1y_speed_warea_avg', 'gyro1y_speed_warea_rms', 'gyro1y_speed_warea_crest',
                        'gyro1y_speed_warea_std', 'gyro1z_speed_wangle_avg', 'gyro1z_speed_wangle_rms',
                        'gyro1z_speed_wangle_crest', 'gyro1z_speed_wangle_std', 'gyro1z_speed_warea_avg',
                        'gyro1z_speed_warea_rms', 'gyro1z_speed_warea_crest', 'gyro1z_speed_warea_std',
                        'gyro1Vec_speed_wangle_avg', 'gyro1Vec_speed_wangle_rms', 'gyro1Vec_speed_wangle_crest',
                        'gyro1Vec_speed_wangle_std', 'gyro1Vec_speed_warea_avg', 'gyro1Vec_speed_warea_rms',
                        'gyro1Vec_speed_warea_crest', 'gyro1Vec_speed_warea_std', 'gyro2x_speed_wangle_avg',
                        'gyro2x_speed_wangle_rms', 'gyro2x_speed_wangle_crest', 'gyro2x_speed_wangle_std',
                        'gyro2x_speed_warea_avg', 'gyro2x_speed_warea_rms', 'gyro2x_speed_warea_crest',
                        'gyro2x_speed_warea_std', 'gyro2y_speed_wangle_avg', 'gyro2y_speed_wangle_rms',
                        'gyro2y_speed_wangle_crest', 'gyro2y_speed_wangle_std', 'gyro2y_speed_warea_avg',
                        'gyro2y_speed_warea_rms', 'gyro2y_speed_warea_crest', 'gyro2y_speed_warea_std',
                        'gyro2z_speed_wangle_avg', 'gyro2z_speed_wangle_rms', 'gyro2z_speed_wangle_crest',
                        'gyro2z_speed_wangle_std', 'gyro2z_speed_warea_avg', 'gyro2z_speed_warea_rms',
                        'gyro2z_speed_warea_crest', 'gyro2z_speed_warea_std', 'gyro2Vec_speed_wangle_avg',
                        'gyro2Vec_speed_wangle_rms', 'gyro2Vec_speed_wangle_crest', 'gyro2Vec_speed_wangle_std',
                        'gyro2Vec_speed_warea_avg', 'gyro2Vec_speed_warea_rms', 'gyro2Vec_speed_warea_crest',
                        'gyro2Vec_speed_warea_std', 'gyro1x_acc_wangle_avg', 'gyro1x_acc_wangle_rms',
                        'gyro1x_acc_wangle_crest', 'gyro1x_acc_wangle_std', 'gyro1x_acc_warea_avg',
                        'gyro1x_acc_warea_rms', 'gyro1x_acc_warea_crest', 'gyro1x_acc_warea_std',
                        'gyro1y_acc_wangle_avg', 'gyro1y_acc_wangle_rms', 'gyro1y_acc_wangle_crest',
                        'gyro1y_acc_wangle_std', 'gyro1y_acc_warea_avg', 'gyro1y_acc_warea_rms',
                        'gyro1y_acc_warea_crest', 'gyro1y_acc_warea_std', 'gyro1z_acc_wangle_avg',
                        'gyro1z_acc_wangle_rms', 'gyro1z_acc_wangle_crest', 'gyro1z_acc_wangle_std',
                        'gyro1z_acc_warea_avg', 'gyro1z_acc_warea_rms', 'gyro1z_acc_warea_crest',
                        'gyro1z_acc_warea_std', 'gyro1Vec_acc_wangle_avg', 'gyro1Vec_acc_wangle_rms',
                        'gyro1Vec_acc_wangle_crest', 'gyro1Vec_acc_wangle_std', 'gyro1Vec_acc_warea_avg',
                        'gyro1Vec_acc_warea_rms', 'gyro1Vec_acc_warea_crest', 'gyro1Vec_acc_warea_std',
                        'gyro2x_acc_wangle_avg', 'gyro2x_acc_wangle_rms', 'gyro2x_acc_wangle_crest',
                        'gyro2x_acc_wangle_std', 'gyro2x_acc_warea_avg', 'gyro2x_acc_warea_rms',
                        'gyro2x_acc_warea_crest', 'gyro2x_acc_warea_std', 'gyro2y_acc_wangle_avg',
                        'gyro2y_acc_wangle_rms', 'gyro2y_acc_wangle_crest', 'gyro2y_acc_wangle_std',
                        'gyro2y_acc_warea_avg', 'gyro2y_acc_warea_rms', 'gyro2y_acc_warea_crest',
                        'gyro2y_acc_warea_std', 'gyro2z_acc_wangle_avg', 'gyro2z_acc_wangle_rms',
                        'gyro2z_acc_wangle_crest', 'gyro2z_acc_wangle_std', 'gyro2z_acc_warea_avg',
                        'gyro2z_acc_warea_rms', 'gyro2z_acc_warea_crest', 'gyro2z_acc_warea_std',
                        'gyro2Vec_acc_wangle_avg', 'gyro2Vec_acc_wangle_rms', 'gyro2Vec_acc_wangle_crest',
                        'gyro2Vec_acc_wangle_std', 'gyro2Vec_acc_warea_avg', 'gyro2Vec_acc_warea_rms',
                        'gyro2Vec_acc_warea_crest', 'gyro2Vec_acc_warea_std', 'gyro1x_power_wangle_avg',
                        'gyro1x_power_wangle_rms', 'gyro1x_power_wangle_crest', 'gyro1x_power_wangle_std',
                        'gyro1x_power_warea_avg', 'gyro1x_power_warea_rms', 'gyro1x_power_warea_crest',
                        'gyro1x_power_warea_std', 'gyro1y_power_wangle_avg', 'gyro1y_power_wangle_rms',
                        'gyro1y_power_wangle_crest', 'gyro1y_power_wangle_std', 'gyro1y_power_warea_avg',
                        'gyro1y_power_warea_rms', 'gyro1y_power_warea_crest', 'gyro1y_power_warea_std',
                        'gyro1z_power_wangle_avg', 'gyro1z_power_wangle_rms', 'gyro1z_power_wangle_crest',
                        'gyro1z_power_wangle_std', 'gyro1z_power_warea_avg', 'gyro1z_power_warea_rms',
                        'gyro1z_power_warea_crest', 'gyro1z_power_warea_std', 'gyro1Vec_power_wangle_avg',
                        'gyro1Vec_power_wangle_rms', 'gyro1Vec_power_wangle_crest', 'gyro1Vec_power_wangle_std',
                        'gyro1Vec_power_warea_avg', 'gyro1Vec_power_warea_rms', 'gyro1Vec_power_warea_crest',
                        'gyro1Vec_power_warea_std', 'gyro2x_power_wangle_avg', 'gyro2x_power_wangle_rms',
                        'gyro2x_power_wangle_crest', 'gyro2x_power_wangle_std', 'gyro2x_power_warea_avg',
                        'gyro2x_power_warea_rms', 'gyro2x_power_warea_crest', 'gyro2x_power_warea_std',
                        'gyro2y_power_wangle_avg', 'gyro2y_power_wangle_rms', 'gyro2y_power_wangle_crest',
                        'gyro2y_power_wangle_std', 'gyro2y_power_warea_avg', 'gyro2y_power_warea_rms',
                        'gyro2y_power_warea_crest', 'gyro2y_power_warea_std', 'gyro2z_power_wangle_avg',
                        'gyro2z_power_wangle_rms', 'gyro2z_power_wangle_crest', 'gyro2z_power_wangle_std',
                        'gyro2z_power_warea_avg', 'gyro2z_power_warea_rms', 'gyro2z_power_warea_crest',
                        'gyro2z_power_warea_std', 'gyro2Vec_power_wangle_avg', 'gyro2Vec_power_wangle_rms',
                        'gyro2Vec_power_wangle_crest', 'gyro2Vec_power_wangle_std', 'gyro2Vec_power_warea_avg',
                        'gyro2Vec_power_warea_rms', 'gyro2Vec_power_warea_crest', 'gyro2Vec_power_warea_std',
                        'gyro1x_angle_wangle_avg', 'gyro1x_angle_wangle_rms', 'gyro1x_angle_wangle_crest',
                        'gyro1x_angle_wangle_std', 'gyro1x_angle_warea_avg', 'gyro1x_angle_warea_rms',
                        'gyro1x_angle_warea_crest', 'gyro1x_angle_warea_std', 'gyro1y_angle_wangle_avg',
                        'gyro1y_angle_wangle_rms', 'gyro1y_angle_wangle_crest', 'gyro1y_angle_wangle_std',
                        'gyro1y_angle_warea_avg', 'gyro1y_angle_warea_rms', 'gyro1y_angle_warea_crest',
                        'gyro1y_angle_warea_std', 'gyro1z_angle_wangle_avg', 'gyro1z_angle_wangle_rms',
                        'gyro1z_angle_wangle_crest', 'gyro1z_angle_wangle_std', 'gyro1z_angle_warea_avg',
                        'gyro1z_angle_warea_rms', 'gyro1z_angle_warea_crest', 'gyro1z_angle_warea_std',
                        'gyro1Vec_angle_wangle_avg', 'gyro1Vec_angle_wangle_rms', 'gyro1Vec_angle_wangle_crest',
                        'gyro1Vec_angle_wangle_std', 'gyro1Vec_angle_warea_avg', 'gyro1Vec_angle_warea_rms',
                        'gyro1Vec_angle_warea_crest', 'gyro1Vec_angle_warea_std', 'gyro2x_angle_wangle_avg',
                        'gyro2x_angle_wangle_rms', 'gyro2x_angle_wangle_crest', 'gyro2x_angle_wangle_std',
                        'gyro2x_angle_warea_avg', 'gyro2x_angle_warea_rms', 'gyro2x_angle_warea_crest',
                        'gyro2x_angle_warea_std', 'gyro2y_angle_wangle_avg', 'gyro2y_angle_wangle_rms',
                        'gyro2y_angle_wangle_crest', 'gyro2y_angle_wangle_std', 'gyro2y_angle_warea_avg',
                        'gyro2y_angle_warea_rms', 'gyro2y_angle_warea_crest', 'gyro2y_angle_warea_std',
                        'gyro2z_angle_wangle_avg', 'gyro2z_angle_wangle_rms', 'gyro2z_angle_wangle_crest',
                        'gyro2z_angle_wangle_std', 'gyro2z_angle_warea_avg', 'gyro2z_angle_warea_rms',
                        'gyro2z_angle_warea_crest', 'gyro2z_angle_warea_std', 'gyro2Vec_angle_wangle_avg',
                        'gyro2Vec_angle_wangle_rms', 'gyro2Vec_angle_wangle_crest', 'gyro2Vec_angle_wangle_std',
                        'gyro2Vec_angle_warea_avg', 'gyro2Vec_angle_warea_rms', 'gyro2Vec_angle_warea_crest',
                        'gyro2Vec_angle_warea_std', 'gyro2Vec_taps_min', 'gyro2Vec_taps_max', 'gyro2Vec_taps_avg',
                        'gyro2Vec_taps_rms', 'gyro2Vec_taps_crest', 'gyro2Vec_taps_std', 'gyro1x_max_val',
                        'gyro1x_max_frequency', 'gyro1x_delta_frequency', 'gyro1x_median_frequency',
                        'gyro1x_median_pow', 'gyro1x_frequency_ratio', 'gyro1x_median_frequency1',
                        'gyro1x_median_frequency2', 'gyro1x_dc_value', 'gyro1x_frequency_ratio1', 'gyro1y_max_val',
                        'gyro1y_max_frequency', 'gyro1y_delta_frequency', 'gyro1y_median_frequency',
                        'gyro1y_median_pow', 'gyro1y_frequency_ratio', 'gyro1y_median_frequency1',
                        'gyro1y_median_frequency2', 'gyro1y_dc_value', 'gyro1y_frequency_ratio1', 'gyro1z_max_val',
                        'gyro1z_max_frequency', 'gyro1z_delta_frequency', 'gyro1z_median_frequency',
                        'gyro1z_median_pow', 'gyro1z_frequency_ratio', 'gyro1z_median_frequency1',
                        'gyro1z_median_frequency2', 'gyro1z_dc_value', 'gyro1z_frequency_ratio1', 'gyro1Vec_max_val',
                        'gyro1Vec_max_frequency', 'gyro1Vec_delta_frequency', 'gyro1Vec_median_frequency',
                        'gyro1Vec_median_pow', 'gyro1Vec_frequency_ratio', 'gyro1Vec_median_frequency1',
                        'gyro1Vec_median_frequency2', 'gyro1Vec_dc_value', 'gyro1Vec_frequency_ratio1',
                        'gyro2x_max_val', 'gyro2x_max_frequency', 'gyro2x_delta_frequency', 'gyro2x_median_frequency',
                        'gyro2x_median_pow', 'gyro2x_frequency_ratio', 'gyro2x_median_frequency1',
                        'gyro2x_median_frequency2', 'gyro2x_dc_value', 'gyro2x_frequency_ratio1', 'gyro2y_max_val',
                        'gyro2y_max_frequency', 'gyro2y_delta_frequency', 'gyro2y_median_frequency',
                        'gyro2y_median_pow', 'gyro2y_frequency_ratio', 'gyro2y_median_frequency1',
                        'gyro2y_median_frequency2', 'gyro2y_dc_value', 'gyro2y_frequency_ratio1', 'gyro2z_max_val',
                        'gyro2z_max_frequency', 'gyro2z_delta_frequency', 'gyro2z_median_frequency',
                        'gyro2z_median_pow', 'gyro2z_frequency_ratio', 'gyro2z_median_frequency1',
                        'gyro2z_median_frequency2', 'gyro2z_dc_value', 'gyro2z_frequency_ratio1', 'gyro2Vec_max_val',
                        'gyro2Vec_max_frequency', 'gyro2Vec_delta_frequency', 'gyro2Vec_median_frequency',
                        'gyro2Vec_median_pow', 'gyro2Vec_frequency_ratio', 'gyro2Vec_median_frequency1',
                        'gyro2Vec_median_frequency2', 'gyro2Vec_dc_value', 'gyro2Vec_frequency_ratio1']

used_artefacts_mix33 = ['gyro1x_max_speed_angle', 'gyro1x_max_speed_area', 'gyro1y_max_speed_angle',
                        'gyro1y_max_speed_area', 'gyro1z_max_speed_angle', 'gyro1z_max_speed_area',
                        'gyro1Vec_max_speed_angle', 'gyro1Vec_max_speed_area', 'gyro2x_max_speed_angle',
                        'gyro2x_max_speed_area', 'gyro2y_max_speed_angle', 'gyro2y_max_speed_area',
                        'gyro2z_max_speed_angle', 'gyro2z_max_speed_area', 'gyro2Vec_max_speed_angle',
                        'gyro2Vec_max_speed_area',
                        'gyro1x_max_acc_angle', 'gyro1x_max_acc_area', 'gyro1y_max_acc_angle',
                        'gyro1y_max_acc_area', 'gyro1z_max_acc_angle', 'gyro1z_max_acc_area',
                        'gyro1Vec_max_acc_angle', 'gyro1Vec_max_acc_area', 'gyro2x_max_acc_angle',
                        'gyro2x_max_acc_area', 'gyro2y_max_acc_angle', 'gyro2y_max_acc_area',
                        'gyro2z_max_acc_angle', 'gyro2z_max_acc_area', 'gyro2Vec_max_acc_angle',
                        'gyro2Vec_max_acc_area',
                        'gyro1x_max_power_angle', 'gyro1x_max_power_area', 'gyro1y_max_power_angle',
                        'gyro1y_max_power_area', 'gyro1z_max_power_angle', 'gyro1z_max_power_area',
                        'gyro1Vec_max_power_angle', 'gyro1Vec_max_power_area', 'gyro2x_max_power_angle',
                        'gyro2x_max_power_area', 'gyro2y_max_power_angle', 'gyro2y_max_power_area',
                        'gyro2z_max_power_angle', 'gyro2z_max_power_area', 'gyro2Vec_max_power_angle',
                        'gyro2Vec_max_power_area',
                        'gyro1x_max_angle_angle', 'gyro1x_max_angle_area', 'gyro1y_max_angle_angle',
                        'gyro1y_max_angle_area', 'gyro1z_max_angle_angle', 'gyro1z_max_angle_area',
                        'gyro1Vec_max_angle_angle', 'gyro1Vec_max_angle_area', 'gyro2x_max_angle_angle',
                        'gyro2x_max_angle_area', 'gyro2y_max_angle_angle', 'gyro2y_max_angle_area',
                        'gyro2z_max_angle_angle', 'gyro2z_max_angle_area', 'gyro2Vec_max_angle_angle',
                        'gyro2Vec_max_angle_area'
                        ]

used_artefacts_mix34 = ['gyro2y_acc_rms', 'gyro2x_power_avg', 'gyro1x_max_val', 'gyro2Vec_median_frequency',
                        'gyro2y_max_speed_avg', 'gyro1z_max_acc_std',

                        'gyro1x_median_change', 'gyro1y_median_change', 'gyro1z_median_change',
                        'gyro1Vec_median_change', 'gyro2x_median_change', 'gyro2y_median_change',
                        'gyro2z_median_change', 'gyro2Vec_median_change'
                        ]

used_artefacts = used_artefacts_mix29


def filtering(artefacts):
    for artefact in artefacts:
        values = []
        for used_artefact in used_artefacts:
            values.append(artefact.dict_values[used_artefact].value)

        artefact.values = values
    return artefacts


def get_filtered_names():
    result = ''
    for used_artefact in used_artefacts:
        if result == '':
            result = used_artefact
        else:
            result = result + '\n' + used_artefact
    return result


def get_filters(artefacts):
    ars = set()
    for artefact in artefacts:
        ars.add(artefact)

    result = 0
    i = 0
    for used_artefact in used_artefacts:
        if used_artefact in ars:
            result = result | (1 << i)
        i = i + 1
    return result


def get_all_names(artefacts):
    artefact = artefacts[0]
    result = ''
    for used_artefact in artefact.dict_values:
        if result == '':
            result = used_artefact
        else:
            result = result + '\n' + used_artefact
    return result


def get_filtered_selected_names(selector):
    result = ''
    for used_artefact in used_artefacts:
        if selector & 1 == 1:
            if result == '':
                result = used_artefact
            else:
                result = result + '\t' + used_artefact
        selector = selector // 2
    return result
